apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: IMAGE_TEMPLATE
  newName: henrygd/beszel-agent
  newTag: 0.10.2

# patches:
# - path: ./patch.yaml

namespace: monitoring