apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace configuration
namespace: backstage

imageTags:
  - name: IMAGE_NAME
    newName: codesenju/backstage
    newTag: 1.0.0

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: backstage-postgres-secrets
  envs:
    - .env

resources:
- ../../base