apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace configuration
namespace: backstage

imageTags:
  - name: IMAGE_NAME
    newName: "ghcr.io/codesenju/backstage"
    newTag: "b8743bc"

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: backstage-postgres-secrets
  envs:
    - .env

resources:
- ../../base