apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8n_image
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          env:
            - name: GENERIC_TIMEZONE
              value: "UTC"
            - name: TZ
              value: "Etc/GMT-2"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n"
            - name: DB_POSTGRESDB_HOST
              value: "n8n-postgres-rw"
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_USER
              value: "n8n"
            - name: DB_POSTGRESDB_SCHEMA
              value: "public"
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-postgres-secrets
                  key: password
            - name: N8N_HOST
              valueFrom:
                configMapKeyRef:
                  name: n8n-env
                  key: N8N_HOST
            - name: N8N_PORT
              valueFrom:
                configMapKeyRef:
                  name: n8n-env
                  key: N8N_PORT
            - name: N8N_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: n8n-env
                  key: N8N_PROTOCOL
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: n8n-env
                  key: WEBHOOK_URL
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
              subPath: n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
