apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-data
  labels:
    service: n8n-data  # This matches the PVC selector
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16 # change me
    path: /mnt/pool1/AppData/
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: n8n-data # Add selector to match PV label
  storageClassName: "" # This prevents dynamic provisioning
