apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/component: indexer-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9696
    targetPort: 9696
  selector:
    app: prowlarr