apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: gitea-runner-config
    files:
      - config.yaml=config.yaml
    options:
      disableNameSuffixHash: true

resources:
- ../../base