apiVersion: v1
kind: PersistentVolume
metadata:
  name: headplane-data
  labels:
    service: headplane-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/k8s-storage/headplane
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  labels:
    app: headplane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: headplane-data
  storageClassName: ""
