apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace configuration
namespace: ddns

images:
- name: favonia/cloudflare-ddns
  newName: favonia/cloudflare-ddns
  newTag: 1.15.1

patches:
- path: patch.yaml

resources:
- ../../base
