apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns  # Must match original Deployment name
spec:
  template:
    spec:
      containers:
      - name: cloudflare-ddns  # Must match container name
        env:
        - name: TZ
          value: "Etc/GMT-2"  # Sets timezone
        resources:
          requests:
            cpu: "64m"
            memory: "64Mi"
          limits:
            cpu: "128m"
            memory: "128Mi"