apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotify-data
  labels:
    service: gotify-data
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16
    path: /mnt/pool1/AppData
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: gotify-data
  storageClassName: ""