apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: obi
  name: obi
spec:
  selector:
    matchLabels:
      instrumentation: obi
  template:
    metadata:
      labels:
        instrumentation: obi
    spec:
      serviceAccount: obi
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: obi
        resources:
          limits:
            memory: 1Gi
        terminationMessagePolicy: FallbackToLogsOnError
        image: "otel/ebpf-instrument:main"
        imagePullPolicy: "Always"
        env:
          # - name: OTEL_EXPORTER_OTLP_ENDPOINT
          #   value: "http://opentelemetry-kube-stack-gateway-collector.opensearch-operator-system.svc.cluster.local:4317"
          - name: OBI_KUBE_METADATA_ENABLE
            value: "autodetect"
          - name: OTEL_EBPF_CONFIG_PATH
            value: "/config/obi-config.yml"
          - name: OTEL_EBPF_KUBE_CLUSTER_NAME
            value: "kubelab"
        securityContext:
          privileged: true
          runAsUser: 0
          readOnlyRootFilesystem: true
          capabilities:
            add:
              - BPF
              - SYS_PTRACE
              - NET_RAW
              - CHECKPOINT_RESTORE
              - DAC_READ_SEARCH
              - PERFMON
              - NET_ADMIN
        volumeMounts:
          - name: cgroup
            mountPath: /sys/fs/cgroup
          - mountPath: /config
            name: obi-config
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: obi-config
        configMap:
          name: obi-config
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup