apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-fanout
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
    
    exporters:
      otlp/alloy:
        endpoint: alloy.grafana-system.svc.cluster.local:4317
        tls:
          insecure: true
      
      otlp/signoz:
        endpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
        tls:
          insecure: true
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/alloy, otlp/signoz]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/alloy]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/alloy]
