---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-runner-data
  labels:
    service: gitea-runner-data
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16 # change me
    path: /mnt/pool1/AppData/
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      service: gitea-runner-data