---
# Secret for NordVPN OpenVPN credentials
apiVersion: v1
kind: Secret
metadata:
  name: nordvpn-credentials
  namespace: media-stack
type: Opaque
stringData:
  OPENVPN_USER: "x"  # Get from NordVPN dashboard
  OPENVPN_PASSWORD: "x"  # Not your main account password!