apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
      - name: nginx-proxy-manager
        image: IMAGE_TEMPLATE
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 81
          name: admin
        # env:
        # Uncomment if needed:
        # - name: DB_SQLITE_FILE
        #   value: "/data/database.sqlite"
        # - name: DISABLE_IPV6
        #   value: "true"
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: nginx-proxy-manager/data
        - name: data
          mountPath: /etc/letsencrypt
          subPath: nginx-proxy-manager/letsencrypt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: npm-data
      # - name: letsencrypt
      #   persistentVolumeClaim:
      #     claimName: npm-data