apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs-postgres
provisioner: csi.truenas.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  protocol: nfs
  compression: ZSTD
  sync: STANDARD
  nfs.mountOptions: hard,nfsvers=4.1
  nfs.mapAllUser: postgres
  nfs.mapAllGroup: docker