apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-credentials
  ingress:
      spec:
        ingressClassName: "traefik"
        rules:
          - host: grafana.local
            http:
              paths:
                - backend:
                    service:
                      name: grafana-service
                      port:
                        number: 3000
                  path: /
                  pathType: Prefix
  config:
    server:
      root_url: 'https://grafana.jazziro.com/'
    # auth.generic_oauth:
    #   allow_sign_up: 'true'
    #   api_url: >-
    #     https://keycloak.lmasu.co.za/realms/master/protocol/openid-connect/userinfo
    #   auth_url: 'https://keycloak.lmasu.co.za/realms/master/protocol/openid-connect/auth'
    #   client_id: grafana
    #   client_secret: oidc-grafana-client-secret
    #   enabled: 'true'
    #   name: keycloak
    #   role_attribute_path: >-
    #     contains(resource_access.grafana.roles[*], 'grafana_admin') && 'Admin'
    #     || contains(resource_access.grafana.roles[*], 'grafana_editor') &&
    #     'Editor' || 'Viewer'
    #   scopes: openid email profile offline_access roles
    #   token_url: 'https://keycloak.lmasu.co.za/realms/master/protocol/openid-connect/token'
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: admin