---
apiVersion: v1
kind: Service
metadata:
  name: instagram-reels-downloader
spec:
  selector:
    app: instagram-reels-downloader
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
