apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: pgcluster
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1beta1
    kind: PGCluster
    group: kubelab.io
    spec:
      # Spec fields that users can provide.
      name: string | required=true immutable=true description="Postgres cluster name"
      # At the time of writing, is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
      image: string | default="ghcr.io/cloudnative-pg/postgresql:16-standard-trixie" # UID 26, GID 102
      instances: integer | default=1
      sharedLibraries: '[]string | default=[] description="List of shared preload libraries"'
      imagePullSecrets: string
      bootstrap:
        mode: string | enum="initdb,recovery" default="initdb" description="initdb or recovery"
      db:
        name: string | required=true
        username: string | required=true
        size: string | default="1Gi"
        storageClassName: string | default=""
        secretName: string | required=true
      recovery:
        backupID: string | description="Backup ID under base/, e.g. 20260402T020003"
        serverName: string | default="${schema.spec.name}-postgres" description="Original source cluster serverName in object store"
      restoreSource:
        s3Path: string | description="Source path to old backups, e.g. s3://cnpg/backups/serverNaame-postgres"
        endpointURL: string
        s3:
          credentialsSecretName: string
          accessKeyId: string
          secretAccessKey: string
      archiveDestination:
        s3Path: string | required=true description="New destination for WAL + future backups, e.g. s3://cnpg/new-backups/serverNaame-postgres"
        endpointURL: string | required=true
        retentionPolicy: string | default="5d"
        s3:
          credentialsSecretName: string | required=true
          accessKeyId: string | required=true
          secretAccessKey: string | required=true
      scheduledBackup:
        enabled: boolean | default=false
        cron: string | default="0 0 2 * * *"

  # Define the resources this API will manage.
  resources:

    - id: restoreObjectStore
      includeWhen:
        - ${schema.spec.bootstrap.mode == "recovery"}
      template:
        apiVersion: barmancloud.cnpg.io/v1
        kind: ObjectStore
        metadata:
          name: ${schema.spec.name}-restore-store
        spec:
          configuration:
            destinationPath: ${schema.spec.restoreSource.s3Path}
            endpointURL: ${schema.spec.restoreSource.endpointURL}
            s3Credentials:
              accessKeyId:
                name: ${schema.spec.restoreSource.s3.credentialsSecretName}
                key: ${schema.spec.restoreSource.s3.accessKeyId}
              secretAccessKey:
                name: ${schema.spec.restoreSource.s3.credentialsSecretName}
                key: ${schema.spec.restoreSource.s3.secretAccessKey}

    - id: archiveObjectStore
      template:
        apiVersion: barmancloud.cnpg.io/v1
        kind: ObjectStore
        metadata:
          name: ${schema.spec.name}-archive-store
        spec:
          configuration:
            destinationPath: ${schema.spec.archiveDestination.s3Path}
            endpointURL: ${schema.spec.archiveDestination.endpointURL}
            s3Credentials:
              accessKeyId:
                name: ${schema.spec.archiveDestination.s3.credentialsSecretName}
                key: ${schema.spec.archiveDestination.s3.accessKeyId}
              secretAccessKey:
                name: ${schema.spec.archiveDestination.s3.credentialsSecretName}
                key: ${schema.spec.archiveDestination.s3.secretAccessKey}
            wal:
              compression: gzip
            data:
              compression: gzip
              jobs: 2
          retentionPolicy: ${schema.spec.archiveDestination.retentionPolicy}

    - id: clusterRecovery
      includeWhen:
        - ${schema.spec.bootstrap.mode == "recovery"} # Only include if recovery mode is selected
      template:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: ${schema.spec.name}-postgres
        spec:
          imageName: ${schema.spec.image}
          instances: ${schema.spec.instances}
          imagePullSecrets: ${schema.spec.imagePullSecrets}
          postgresql:
            shared_preload_libraries: ${schema.spec.sharedLibraries}
          managed:
            roles:
              - name: ${schema.spec.db.username}
                superuser: true
                login: true
          bootstrap:
            recovery:
              source: origin
              recoveryTarget:
                backupID: ${schema.spec.recovery.backupID}
          externalClusters:
            - name: origin
              plugin:
                name: barman-cloud.cloudnative-pg.io
                parameters:
                  barmanObjectName: ${restoreObjectStore.metadata.name}
                  serverName: ${schema.spec.recovery.serverName}
          plugins:
            - name: barman-cloud.cloudnative-pg.io
              isWALArchiver: true
              parameters:
                barmanObjectName: ${archiveObjectStore.metadata.name}
          storage:
            size: ${schema.spec.db.size}
            pvcTemplate:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: ${schema.spec.db.size}
              storageClassName: ${schema.spec.db.storageClassName}

    - id: clusterInit
      includeWhen:
        - ${schema.spec.bootstrap.mode == "initdb"} # Only include if recovery mode is selected
      template:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: ${schema.spec.name}-postgres
        spec:
          imageName: ${schema.spec.image}
          instances: ${schema.spec.instances}
          imagePullSecrets: 
            - name: ${schema.spec.imagePullSecrets}
          postgresql:
            shared_preload_libraries: ${schema.spec.sharedLibraries}
          managed:
            roles:
              - name: ${schema.spec.db.username}
                superuser: true
                login: true
          bootstrap:
            initdb:
              database: ${schema.spec.db.name}
              owner: ${schema.spec.db.username}
              secret:
                name: ${schema.spec.db.secretName}
          plugins:
            - name: barman-cloud.cloudnative-pg.io
              isWALArchiver: true
              parameters:
                barmanObjectName: ${archiveObjectStore.metadata.name}
          storage:
            size: ${schema.spec.db.size}
            pvcTemplate:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: ${schema.spec.db.size}
              storageClassName: ${schema.spec.db.storageClassName}

    - id: scheduledBackup
      includeWhen:
        - ${schema.spec.scheduledBackup.enabled}
      template:
        apiVersion: postgresql.cnpg.io/v1
        kind: ScheduledBackup
        metadata:
          name: ${schema.spec.name}-postgres-daily-s3-backup
          namespace: ${schema.metadata.namespace}
        spec:
          schedule: ${schema.spec.scheduledBackup.cron}
          cluster:
            name: ${schema.spec.name}-postgres
          immediate: true
          backupOwnerReference: self
          method: plugin
          pluginConfiguration:
            name: barman-cloud.cloudnative-pg.io
