apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databasus

images:
- name: IMAGE_PLACEHOLDER
  newName: databasus/databasus
  newTag: v3.32.0 

patches:
  - path: pv.patch.yaml
    target:
      group: ""
      version: v1
      kind: PersistentVolume
      name: databasus-data
  - path: pvc.patch.yaml
    target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: databasus-data

resources:
- ../../base
