---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasus-data
  labels:
    app: databasus
spec:
  $patch: replace
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: databasus-data
  storageClassName: ""
