name: Lint and Spellcheck

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'feat*'

env:
  CLICOLOR: 1

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up lint tools
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install codespell
          pip install ansible-lint
          pip install yamllint

      - name: Run codespell on Markdown files
        run: |
          . .venv/bin/activate
          codespell --version
          codespell --ignore-words-list="mke,teh" --skip="*.py,*.yml,*.yaml" .

      - name: Run ansible-lint on Ansible files
        run: |
          . .venv/bin/activate
          ansible-lint --version
          ansible-lint --exclude .venv .

      - name: Run ansible-lint on all Ansible files
        run: |
          . .venv/bin/activate
          ansible-lint *ansible **/*ansible **/**/*ansible || true

      - name: Run yamllint on YAML files
        run: |
          . .venv/bin/activate
          yamllint --version
          yamllint --no-warnings . || true
