name: Spellcheck Documentation

on:
  push:
    paths:
      - '**/**/*.md'
      - '**/*.md'
      - '*.md'
  pull_request:
    paths:
      - '**/**/*.md'
      - '**/*.md'
      - '*.md'
  
env:
  CLICOLOR: 1

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Spelling
        uses: crate-ci/typos@v1.33.1
        with:
          files: |
            **/**/*.md
            **/*.md
            *.md

      - name: Ensure pipx is installed
        run: python3 -m pip install --user pipx && python3 -m pipx ensurepath

      - name: Install codespell
        run: pipx install codespell

      - name: Run codespell on Markdown files
        run: pipx run codespell --ignore-words-list="mke,teh" --skip="*.py,*.yml,*.yaml" .
