name: Spellcheck Documentation

on:
  push:
    paths:
      - '**/**/*.md'
      - '**/*.md'
      - '*.md'
  pull_request:
    paths:
      - '**/**/*.md'
      - '**/*.md'
      - '*.md'

jobs:
  spellcheck:
    runs-on: static-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Spelling
        uses: crate-ci/typos@v1.33.1

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell on Markdown files
        run: codespell --ignore-words-list="mke,teh" --skip="*.py,*.yml,*.yaml" .
