apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - ../../base/
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: n8n-postgres-secrets
  envs:
    - .env