apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

images:
- name: n8n_image
  newName: codesenju/n8n
  newTag: 1.110.1

resources:
  - ../../base/
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: n8n-postgres-secrets
  envs:
    - .env