apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

# update image
images:
- name: IMAGE_TEMPLATE
  newName: pihole/pihole
  newTag: 2025.03.1

patches:
- path: patch.yaml

# Shared resources across all apps
resources:
- ../../base