apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/component: media-server
spec:
  template:
    spec:
      containers:
      - name: jellyseerr
        volumeMounts:
        - name: data
          mountPath: /data/movies
          subPath: movies
        - name: data
          mountPath: /data/tv
          subPath: tv
        - name: data
          mountPath: /data/music
          subPath: music
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app.kubernetes.io/component: request-management
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.56