apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/component: media-server
spec:
  template:
    spec:
      containers:
      - name: jellyfin
        env:
        - name: JELLYFIN_PublishedServerUrl
          valueFrom:
            configMapKeyRef:
              name: media-stack-env
              key: JELLYFIN_URL
        volumeMounts:
        - name: data
          mountPath: /data/media/movies
          subPath: movies
        - name: data
          mountPath: /data/media/tv
          subPath: tv
        - name: data
          mountPath: /data/media/music
          subPath: music
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: media-data