apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  template:
    spec:
      containers:
      - name: lidarr
        env:
        - name: LIDARR__INSTANCE_NAME
          value: "Lidarr-Prod"
        - name: LIDARR__DOWNLOADCLIENT__1__DOWNLOADDIR
          value: "/downloads"
        - name: LIDARR__MEDIADIR
          value: "/data/music"
        volumeMounts:
        - name: data
          mountPath: /data/music
          subPath: music
        - name: data
          mountPath: /downloads
          subPath: downloads
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lidarr
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.0.88