apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    spec:
      containers:
      - name: prowlarr
        env:
        - name: PROWLARR__INSTANCE_NAME
          value: "Prowlarr-Prod"
        resources:
          requests:
            cpu: 15m
            memory: 226M
          limits:
            cpu: 15m
            memory: 226M
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prowlarr
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.0.84