apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    spec:
      containers:
      - name: prowlarr
        env:
        - name: PROWLARR__INSTANCE_NAME
          value: "Prowlarr-Prod"