apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    spec:
      containers:
      - name: qbittorrent
        env:
        - name: QBITTORRENT_CATEGORIES
          value: "movies=/downloads/torrents/movies,tv=/downloads/torrents/tv,music=/downloads/torrents/music,books=/downloads/torrents/books"
        - name: DOWNLOADS_LOCATION
          value: "/data/downloads"
        volumeMounts:
        - name: data
          mountPath: /downloads/torrents
          subPath: downloads/torrents
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.83