apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  template:
    spec:
      containers:
      - name: sonarr
        env:
        - name: SONARR__INSTANCE_NAME
          value: "Sonarr-Prod"
        - name: QBITTORRENT__HOST
          value: "qbittorrent"
        - name: QBITTORRENT__PORT
          value: "8080"
        - name: SONARR__DOWNLOADCLIENT__1__DOWNLOADDIR
          value: "/downloads"
        - name: SONARR__MEDIADIR
          value: "/data/tv"
        volumeMounts:
        - name: data
          mountPath: /data/tv
          subPath: tv
        - name: data
          mountPath: /downloads
          subPath: downloads
        resources:
          requests:
            cpu: 23m
            memory: 324M
          limits:
            cpu: 23m
            memory: 324M
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sonarr
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 192.168.0.81