apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app.kubernetes.io/component: request-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
        app.kubernetes.io/component: request-management
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: seerr
        image: docker.io/fallenbagel/seerr:2.5.1
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: global-env
        ports:
        - containerPort: 5055
          name: http
        volumeMounts:
        - name: media-stack-config
          mountPath: /app/config
          subPath: seerr/config
        resources:
          requests:
            cpu: "64m"
            memory: "128Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
      volumes:
      - name: media-stack-config
        persistentVolumeClaim:
          claimName: media-stack-config
