apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: binfmt
spec:
  selector:
    matchLabels:
      app: binfmt
  template:
    metadata:
      labels:
        app: binfmt
    spec:
      hostPID: true
      tolerations:
        - operator: Exists
      containers:
        - name: binfmt
          image: tonistiigi/binfmt:latest
          securityContext:
            privileged: true
          args:
            - --install
            - arm64
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
            type: Directory
