apiVersion: batch/v1
kind: Job
metadata:
  name: binfmt
  namespace: kube-system
spec:
  template:
    spec:
      hostPID: true
      restartPolicy: OnFailure
      tolerations:
        - operator: Exists
      containers:
        - name: binfmt
          image: tonistiigi/binfmt:latest
          securityContext:
            privileged: true
          args:
            - --install
            - arm64
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
