apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao-transit

resources:
  - ../../base

images:
  - name: IMAGE_PLACEHOLDER
    newName: openbao/openbao
    newTag: 2.7.0
