- name: Install k9s
  hosts: k8s-control-plane-1
  become: no
  gather_facts: false
  vars:
    namespace: argocd
  tasks:
# kubectl get crd -o name | grep argoproj.io | xargs kubectl delete
    - name: Deploy Argocd
      kubernetes.core.helm:
        name: argocd
        state: present
        chart_repo_url: https://argoproj.github.io/argo-helm
        chart_ref: argo-cd
        chart_version: 8.2.5
        release_namespace: '{{ namespace }}'
        create_namespace: true
        release_values:
          global:
            domain: "{{ argocd_domain }}"
          controller:
            replicas: 1
            metrics:
              enabled: true
              serviceMonitor:
                enabled: false
          server:
            replicas: 2
            metrics:
              enabled: true
              serviceMonitor:
                enabled: false
          repoServer:
            replicas: 2
            metrics:
              enabled: true
              serviceMonitor:
                enabled: false
          applicationSet:
            replicas: 2
            metrics:
              enabled: true
              serviceMonitor:
                enabled: false
          configs:
            # secret:
            #   extra:
            #     dex.authentik.clientSecret: "{{ argocd_openid_client_secret }}"
            rbac:
              policy.csv: |
                 g, ArgoCD Admins, role:admin
                 g, authentik Admins, role:admin
                 g, ArgoCD Viewers, role:readonly
                 g, jazziro-kubelab:kubelab, role:readonly
            cm:
              admin.enabled: true
              exec.enabled: true
              dex.config: |
                connectors:
                # https://github.com/dexidp/website/blob/main/content/docs/connectors/github.md
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: "{{ github_client_id }}"
                    clientSecret: "{{ github_client_secret }}"
                    orgs:
                    - name: jazziro-kubelab
                      teams:
                      - kubelab
                # Authentik OIDC connector configuration
                - type: oidc
                  name: authentik
                  id: authentik
                  config:
                    issuer: "{{ argocd_openid_issuer_url }}"
                    redirectURI: "{{ argocd_openid_redirect_uri }}"
                    clientID: argocd
                    clientSecret: "{{ argocd_openid_client_secret }}"
                    insecureEnableGroups: true
                    scopes:
                      - openid
                      - profile
                      - email
            params:
              server.insecure: true
          redis-ha:
            enabled: false
          dex:
            enabled: true
            # extraArgs:
            #   - --disable-tls 
    # - name: Wait for ArgoCD pods to be ready
    #   kubernetes.core.k8s_info:
    #     kind: Pod
    #     namespace: argocd
    #     label_selectors:
    #       - app.kubernetes.io/part-of=argocd
    #     wait: yes
    #     wait_sleep: 10
    #     wait_timeout: 300
    #     wait_condition:
    #       type: Ready
    #       status: "True"

    - name: Get Argo CD admin password
      shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password
      changed_when: false

    - name: Get LoadBalancer IP
      shell: kubectl -n argocd get svc argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: lb_ip
      changed_when: false

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com
            namespace: '{{ namespace }}'
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ dns_name_2 }}"
            dnsNames:
            - "{{ dns_name_1 }}"
            - "{{ dns_name_2 }}"

    - name: Create Traefik dashboard IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: argocd-server
            namespace: '{{ namespace }}'
            annotations:
              kubernetes.io/ingress.class: traefik
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`argocd.{{ dns_name_1 }}`)
                kind: Rule
                services:
                  - name: argocd-server
                    kind: Service
                    port: 80
            tls:
              secretName: local-jazziro-com-tls

    - name: Create ServiceMonitor for ArgoCD Application Controller
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: argocd-metrics
            namespace: '{{ namespace }}'
            labels:
              release: kube-prometheus-stack
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: argocd-metrics
            endpoints:
              - port: http-metrics

    - name: Create ServiceMonitor for ArgoCD Server
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: argocd-server-metrics
            namespace: '{{ namespace }}'
            labels:
              release: kube-prometheus-stack
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: argocd-server-metrics
            endpoints:
              - port: http-metrics

    - name: Create ServiceMonitor for ArgoCD Repo Server
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: argocd-repo-server-metrics
            namespace: '{{ namespace }}'
            labels:
              release: kube-prometheus-stack
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: argocd-repo-server
            endpoints:
              - port: http-metrics

    - name: Create ServiceMonitor for ArgoCD ApplicationSet Controller
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: argocd-applicationset-controller-metrics
            namespace: '{{ namespace }}'
            labels:
              release: kube-prometheus-stack
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: argocd-applicationset-controller
            endpoints:
              - port: http-metrics

    - name: Display Argo CD access information
      ansible.builtin.debug:
        msg:
          - "----------------------------------------"
          - "🚀 Argo CD deployed successfully!"
          - "----------------------------------------"
          - "📍 URL:       http://{{ lb_ip.stdout }}"
          - "👤 Username:  admin"
          - "🔑 Password:  {{ argocd_password.stdout }}"
          - "----------------------------------------"
