- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  tasks:

    - name: Deploy backstage
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: backstage
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: ghcr.io/backstage/charts
              chart: backstage
              targetRevision: 2.5.3
              kustomize:
                # Add these to your existing kustomize config
                labels:
                  app.kubernetes.io/instance: backstage
            destination:
              server: https://kubernetes.default.svc
              namespace: backstage
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true
            # ignoreDifferences:
            #   - group: "postgresql.cnpg.io"
            #     kind: Cluster
            #     jsonPointers:
            #       - /spec/managed/roles