- hosts: k8s-control-plane-1
  gather_facts: no
  vars:
    target_namespace: binfmt
  tasks:

    - name: Deploy binfmt
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: binfmt
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/binfmt/overlays/prod
              targetRevision: binfmt
              kustomize:
                # Add these to your existing kustomize config
                labels:
                  app.kubernetes.io/instance: binfmt
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true