- hosts: k8s-control-plane-1
  gather_facts: no
  vars:
    target_namespace: cloudbeaver
  tasks:

    - name: Deploy cloudbeaver ArgoCD Application
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: cloudbeaver
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/cloudbeaver/overlays/prod
              targetRevision: main
              kustomize:
                patches:
                  - target:
                      group: apps
                      version: v1
                      kind: PersistentVolumeClaim
                      name: cloudbeaver-data
                    patch: |-
                      - op: add
                        path: /spec/storageClassName
                        value: nfs-csi
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{ target_namespace }}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
      tags: cloudbeaver
      when: false

    - name: Deploy postgres
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: cloudbeaver-postgres
            namespace: "{{ target_namespace }}"
          spec:
            # At the time of writing, is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
            imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba # UID 26, GID 999
            instances: 1
            postgresql:
              shared_preload_libraries:
                - "vectors.so"
            managed:
              roles:
                - name: cloudbeaver
                  superuser: true
                  login: true
            bootstrap:
              initdb:
                database: cloudbeaver
                owner: cloudbeaver
                secret:
                  name: cloudbeaver-postgres-secrets
                postInitSQL:
                  - CREATE EXTENSION IF NOT EXISTS "vectors";
                  - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
                  - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
            storage:
              size: 1Gi
              pvcTemplate:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: "proxmox-csi"
            backup:
              # 3-day retention for both base backups and WALsgit
              retentionPolicy: "3d"
              barmanObjectStore:
                destinationPath: s3://cnpg/backups
                # Only needed if NOT using AWS (e.g., MinIO or DigitalOcean)
                endpointURL: "https://{{ rustfs_endpoint }}"
                s3Credentials:
                  accessKeyId:
                    name: s3-creds
                    key: ACCESS_KEY_ID
                  secretAccessKey:
                    name: s3-creds
                    key: SECRET_ACCESS_KEY
                wal:
                  compression: gzip
                data:
                  compression: gzip
                  jobs: 2
      tags:
        - postgres

    - name: Create cloudbeaver postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudbeaver-postgres-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ cloudbeaver_db_username }}"
            password: "{{ cloudbeaver_db_password }}"
      tags:
      - postgres

    - name: Create postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            ACCESS_KEY_ID: "{{ rustfs_access_key }}"
            SECRET_ACCESS_KEY: "{{ rustfs_secret_key }}"
      tags:
        - postgres

    - name: Deploy ScheduledBackup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: ScheduledBackup
          metadata:
            name: daily-s3-backup
            namespace: "{{ target_namespace }}"
          spec:
            # Standard Cron: s m h dom mon dow
            # This runs every day at 2:00 AM
            schedule: "0 0 2 * * *"
            cluster:
              name: cloudbeaver-postgres
            # Setting this to true takes a backup immediately upon creation
            immediate: true
            # 'self' means this ScheduledBackup object owns the resulting Backup records
            backupOwnerReference: self
      tags:
        - postgres

    - name: Deploy cloudbeaver
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: cloudbeaver
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/dbeaver/cloudbeaver-deploy.git
              path: k8s
              targetRevision: HEAD
              helm:
                values: |
                  cloudbeaver:
                    replicaCount: 1
                    image: harbor.jazziro.com/dockerio/dbeaver/cloudbeaver
                    imageTag: "26.0.0"
                    pullPolicy: IfNotPresent
                    pullCredsName: harbor-secret
                  cloudbeaverBaseDomain: "cloudbeaver.local.jazziro.com"
                  httpScheme: http
                  cloudProvider: None
                  storage:
                    storageClassName: "truenas-nfs-zstd"
                  backend:
                    internal_db: false
                    cloudbeaver_db_driver: postgres-jdbc
                    # The full JDBC URL:
                    cloudbeaver_db_url: jdbc:postgresql://cloudbeaver-postgres-rw.cloudbeaver.svc.cluster.local:5432/cloudbeaver
                    cloudbeaver_db_user: cloudbeaver
                    cloudbeaver_db_password: "{{ cloudbeaver_db_password }}"
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true
      tags:
      - cloudbeaver
      # when: false

    - name: Create Harbor pull secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: harbor-secret
            namespace: '{{ target_namespace }}'
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ {'auths': {'https://' + harbor_domain: {'username': harbor_username, 'password': harbor_password, 'auth': (harbor_username + ':' + harbor_password) | b64encode}}} | to_json | b64encode }}"

    - name: Create HTTPRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: cloudbeaver
            namespace: "{{ target_namespace }}"
          spec:
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: websecure
            hostnames:
              - "cloudbeaver.{{ local_dns }}"
            rules:
              - backendRefs:
                  - name: cloudbeaver
                    port: 8978
      tags: 
      - ingress

    - name: Create HTTPRoute http redirect
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: cloudbeaver-redirect
            namespace: cloudbeaver
          spec:
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: web
            hostnames:
              - "cloudbeaver.{{ local_dns }}"
            rules:
              - filters:
                  - type: RequestRedirect
                    requestRedirect:
                      scheme: https
                      statusCode: 301
                      port: 443
      tags: 
      - ingress
