- hosts: k8s-control-plane-1
  become: no
  gather_facts: no
  vars:
    target_namespace: coder
  tasks:

    - name: Create coder postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: coder-postgres-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ coder_db_username }}"
            password: "{{ coder_db_password }}"

    - name: Create coder postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            ACCESS_KEY_ID: "{{ rustfs_access_key }}"
            SECRET_ACCESS_KEY: "{{ rustfs_secret_key }}"

    - name: Create s3 secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ coder_db_username }}"
            password: "{{ coder_db_password }}"

    - name: Deploy coder postgres cluster
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: coder-postgres
            namespace: "{{ target_namespace }}"
          spec:
            # At the time of writing, coder is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
            imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba # UID 26, GID 999
            instances: 1
            postgresql:
              shared_preload_libraries:
                - "vectors.so"
            bootstrap:
              initdb:
                database: coder
                owner: coder
                secret:
                  name: coder-postgres-secrets
                postInitSQL:
                  - CREATE EXTENSION IF NOT EXISTS "vectors";
                  - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
                  - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
            storage:
              size: 5Gi
              pvcTemplate:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
                # storageClassName: ""
            backup:
              # 3-day retention for both base backups and WALsgit
              retentionPolicy: "3d"
              barmanObjectStore:
                destinationPath: s3://cnpg/backups
                # Only needed if NOT using AWS (e.g., MinIO or DigitalOcean)
                endpointURL: "https://{{ rustfs_endpoint }}"
                s3Credentials:
                  accessKeyId:
                    name: s3-creds
                    key: ACCESS_KEY_ID
                  secretAccessKey:
                    name: s3-creds
                    key: SECRET_ACCESS_KEY
                wal:
                  compression: gzip
                data:
                  compression: gzip
                  jobs: 2

    - name: Deploy ScheduledBackup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: ScheduledBackup
          metadata:
            name: daily-s3-backup
            namespace: '{{ target_namespace }}'
          spec:
            # Standard Cron: s m h dom mon dow
            # This runs every day at 2:00 AM
            schedule: "0 0 2 * * *"
            cluster:
              name: coder-postgres
            # Setting this to true takes a backup immediately upon creation
            immediate: true
            # 'self' means this ScheduledBackup object owns the resulting Backup records
            backupOwnerReference: self

    - name: Create coder db url
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: coder-config
            namespace: '{{ target_namespace }}'
          type: Opaque
          stringData:
            url: "{{ coder_db_url }}"
            coder_access_url: "https://coder.{{ local_dns }}"

    - name: Deploy Coder
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: coder
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: coder
              repoURL: https://helm.coder.com/v2
              targetRevision: 2.31.5
              helm:
                releaseName: coder
                values: |
                  coder:
                    env:
                      - name: CODER_PG_CONNECTION_URL
                        valueFrom:
                          secretKeyRef:
                            name: coder-config
                            key: url
                      - name: CODER_ACCESS_URL
                        valueFrom:
                          secretKeyRef:
                            name: coder-config
                            key: coder_access_url
                      - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
                        value: "false"
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{ target_namespace }}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

    - name: Create coder HTTPRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: coder
            namespace: '{{ target_namespace }}'
          spec:
            hostnames:
            - "coder.{{ local_dns }}"
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: websecure
            rules:
              - backendRefs:
                  - name: coder
                    port: 80
