- hosts: k8s-control-plane-1
  become: no
  tasks:

    - name: Deploy Crossplane
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: crossplane
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: crossplane
              repoURL: https://charts.crossplane.io/stable
              targetRevision: 1.20.0
              helm:
                releaseName: crossplane
                # values: |
                #   installCRDs: true
            destination:
              server: https://kubernetes.default.svc
              namespace: crossplane-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Deploy Crossplane provider-kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: pkg.crossplane.io/v1
          kind: Provider
          metadata:
            name: upbound-provider-kubernetes
          spec:
            package: xpkg.upbound.io/upbound/provider-kubernetes:v0.18.0

    - name: Create Crossplane Kubernetes target credentials secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cluster-config
            namespace: crossplane-system
          type: Opaque
          data:
            kubeconfig: "{{ lookup('file', '~/.kube/config') | b64encode }}"

    - name: Create Crossplane ProviderConfig for Kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: ProviderConfig
          metadata:
            name: kubernetes-provider
          spec:
            credentials:
              secretRef:
                key: kubeconfig
                name: cluster-config
                namespace: crossplane-system
              source: Secret
