---
- name: Databasus Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: databasus
  tasks:
    - name: Deploy databasus ArgoCD Application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: databasus
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: "kustomize/databasus/overlays/{{ target_environment }}"
              targetRevision: main
              kustomize:
                images:
                  - databasus/databasus=registry.jazziro.com/dockerio/databasus/databasus:v3.32.0
                patches:
                  - target:
                      kind: Deployment
                      name: databasus
                    patch: |-
                      - op: add
                        path: /spec/template/spec/imagePullSecrets
                        value:
                          - name: {{ registry_name }}
                commonAnnotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                labels:
                  app.kubernetes.io/instance: databasus-prod
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
            ignoreDifferences:
              - group: apps
                kind: StatefulSet
                name: databasus
                jqPathExpressions:
                  - .spec.template.metadata.annotations
                  - .spec.template.metadata.creationTimestamp
                  - .spec.template.spec.containers[].livenessProbe.httpGet.scheme
                  - .spec.template.spec.containers[].livenessProbe.successThreshold
                  - .spec.template.spec.containers[].readinessProbe.httpGet.scheme
                  - .spec.template.spec.containers[].readinessProbe.successThreshold
                  - .spec.template.spec.containers[].terminationMessagePath
                  - .spec.template.spec.containers[].terminationMessagePolicy
                  - .spec.template.spec.dnsPolicy
                  - .spec.template.spec.restartPolicy
                  - .spec.template.spec.schedulerName
                  - .spec.template.spec.securityContext
                  - .spec.template.spec.terminationGracePeriodSeconds
                  - .spec.volumeClaimTemplates[].apiVersion
                  - .spec.volumeClaimTemplates[].kind
                  - .spec.volumeClaimTemplates[].metadata.creationTimestamp
                  - .spec.volumeClaimTemplates[].spec.volumeMode
                  - .spec.volumeClaimTemplates[].status
      tags: databasus
      # when: false

    - name: Deploy Databasus
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: databasus
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: databasus
              repoURL: ghcr.io/databasus/charts
              targetRevision: 3.22.0
              helm:
                releaseName: databasus
                values: |
                  resources:
                    requests:
                      cpu: 25m
                      memory: 128Mi
                    limits:
                      cpu: 250m
                      memory: 256Mi
                  persistence:
                    enabled: true
                    # Storage class name. Leave empty to use cluster default.
                    # Examples: "longhorn", "standard", "gp2", etc.
                    storageClassName: "{{ databasus_sc }}" # leave empty to use default
                    accessMode: ReadWriteOnce
                    size: 10Gi
                    # Mount path in container
                    mountPath: /databasus-data
                  ingress:
                    enabled: false
                    className: traefik
                    annotations:
                       traefik.ingress.kubernetes.io/router.middlewares: "{{ target_namespace }}-redirect-https@kubernetescrd"
                       argocd.argoproj.io/ignore-healthcheck: "true"
                    hosts:
                      - host: 'databasus.{{ local_dns }}'
                        paths:
                          - path: /
                            pathType: Prefix
                    tls:
                    - hosts:
                      - 'databasus.{{ local_dns }}'
                      secretName: local-jazziro-com-tls
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
            ignoreDifferences:
              - group: apps
                kind: StatefulSet
                name: databasus
                jqPathExpressions:
                  - .spec.template.metadata.annotations
                  - .spec.template.metadata.creationTimestamp
                  - .spec.template.spec.containers[].livenessProbe.httpGet.scheme
                  - .spec.template.spec.containers[].livenessProbe.successThreshold
                  - .spec.template.spec.containers[].readinessProbe.httpGet.scheme
                  - .spec.template.spec.containers[].readinessProbe.successThreshold
                  - .spec.template.spec.containers[].terminationMessagePath
                  - .spec.template.spec.containers[].terminationMessagePolicy
                  - .spec.template.spec.dnsPolicy
                  - .spec.template.spec.restartPolicy
                  - .spec.template.spec.schedulerName
                  - .spec.template.spec.securityContext
                  - .spec.template.spec.terminationGracePeriodSeconds
                  - .spec.volumeClaimTemplates[].apiVersion
                  - .spec.volumeClaimTemplates[].kind
                  - .spec.volumeClaimTemplates[].metadata.creationTimestamp
                  - .spec.volumeClaimTemplates[].spec.volumeMode
                  - .spec.volumeClaimTemplates[].status
      when: false

    - name: Create HTTPRoute for databasus
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: databasus
            namespace: "{{ target_namespace }}"
          spec:
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: websecure-public
            hostnames:
              - "databasus.{{ public_dns }}"
            rules:
              - backendRefs:
                  - name: databasus
                    port: 4005
