- name: Create Elastic Synthetic Monitor Agent Policy and ArgoCD Application
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    kbn_headers:
      Content-Type: "application/json"
      kbn-xsrf: "true"
      Authorization: "ApiKey {{ fleet_manager_api_key }}"
    es_headers:
      Content-Type: "application/json"
      Authorization: "ApiKey {{ fleet_manager_api_key }}"
    synthetic_monitor_policy_name: "synthetic-monitor-policy-default"

  tasks:
    - name: Create synthetic monitor agent policy (ignore if exists)
      uri:
        url: "{{ kibana_url }}/api/fleet/agent_policies"
        method: POST
        headers: "{{ kbn_headers }}"
        body_format: json
        body:
          name: "{{ synthetic_monitor_policy_name }}"
          namespace: "default"
          description: "Policy for Elastic Synthetic Monitor agents"
        return_content: yes
        status_code: [200, 201, 409]
      register: create_policy
      failed_when: false

    - name: Get existing policy if creation failed due to conflict
      uri:
        url: "{{ kibana_url }}/api/fleet/agent_policies"
        method: GET
        headers: "{{ kbn_headers }}"
        return_content: yes
      register: existing_policies
      when: create_policy.status == 409

    - name: Find existing policy by name
      set_fact:
        agent_policy_id: "{{ item.id }}"
        agent_policy_name: "{{ item.name }}"
      loop: "{{ existing_policies.json['items'] }}"
      when: 
        - create_policy.status == 409
        - item.name == synthetic_monitor_policy_name

    - name: Save agent policy details (new policy)
      set_fact:
        agent_policy_id: "{{ create_policy.json.item.id }}"
        agent_policy_name: "{{ create_policy.json.item.name }}"
      when: create_policy.status in [200, 201]

    - name: Show policy status
      debug:
        msg: "Agent policy '{{ agent_policy_name }}' (ID: {{ agent_policy_id }}) - {{ 'Created' if create_policy.status in [200, 201] else 'Already exists' }}"

    - name: Create synthetic private location
      uri:
        url: "{{ kibana_url }}/api/synthetics/private_locations"
        method: POST
        headers: "{{ kbn_headers }}"
        body_format: json
        body:
          label: "synthetic-monitor-default"
          agentPolicyId: "{{ agent_policy_id }}"
          tags: ["ansible-managed", "synthetic-monitor", "default", "private"]
          geo:
            lat: 40.7128
            lon: -74.0060
        return_content: yes
        status_code: [200, 201, 409]
      register: private_location_response
      failed_when: false

    - name: Show private location creation status
      debug:
        msg: "Private location: {{ 'Created successfully' if private_location_response.status in [200, 201] else 'Already exists or failed' }}"

    - name: Get private location details if created successfully
      set_fact:
        private_location_id: "{{ private_location_response.json.id }}"
        private_location_label: "{{ private_location_response.json.label }}"
      when: private_location_response.status in [200, 201]

    - name: Get existing private locations if creation failed
      uri:
        url: "{{ kibana_url }}/api/synthetics/private_locations"
        method: GET
        headers: "{{ kbn_headers }}"
        return_content: yes
      register: existing_private_locations
      when: private_location_response.status == 409

    - name: Find existing private location by label
      set_fact:
        private_location_id: "{{ item.id }}"
        private_location_label: "{{ item.label }}"
      loop: "{{ existing_private_locations.json }}"
      when: 
        - private_location_response.status == 409
        - item.label == 'synthetic-monitor-default'

    - name: Get enrollment token for the policy
      uri:
        url: "{{ kibana_url }}/api/fleet/enrollment_api_keys"
        method: POST
        headers: "{{ kbn_headers }}"
        body_format: json
        body:
          name: "synthetic-monitor-enrollment-{{ ansible_date_time.epoch }}"
          policy_id: "{{ agent_policy_id }}"
        return_content: yes
        status_code: [200, 201]
      register: enrollment_token_response

    - name: Save enrollment token
      set_fact:
        synthetic_monitor_enrollment_token: "{{ enrollment_token_response.json.item.api_key }}"

    - name: Show enrollment token created
      debug:
        msg: "Enrollment token created successfully"

    - name: Create synthetic-monitor-config secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: synthetic-monitor-config
            namespace: elastic-system
            labels:
              managed-by: ansible
              component: synthetic-monitor
              app: elastic-stack
          type: Opaque
          stringData:
            FLEET_URL: "{{ fleet_server_default_url }}" # external URL
            FLEET_ENROLLMENT_TOKEN: "{{ synthetic_monitor_enrollment_token }}" # retreived from previous task
            FLEET_ENROLL: "1"
            FLEET_INSECURE: "false"
      register: k8s_secret_result

    - name: Show Kubernetes secret creation result
      debug:
        msg: "Kubernetes secret 'synthetic-monitor-config' created in namespace 'elastic-system'"

    - name: Create ArgoCD Application for Elastic Synthetic Monitor
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: elastic-synthetic-monitor
            namespace: argocd
            labels:
              managed-by: ansible
              component: synthetic-monitor
              app: elastic-stack
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              targetRevision: HEAD
              path: kustomize/elastic-synthetic-monitor/overlays/prod
            destination:
              server: https://kubernetes.default.svc
              namespace: elastic-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      register: argocd_app_result

    - name: Show ArgoCD application creation result
      debug:
        msg: "ArgoCD application 'elastic-synthetic-monitor' created successfully"

    - name: Summary
      debug:
        msg:
          - "Agent Policy: {{ agent_policy_name }} ({{ 'Created' if create_policy.status in [200, 201] else 'Already exists' }})"
          - "Private Location: {{ private_location_label | default('synthetic-monitor-default') }} ({{ 'Created' if private_location_response.status in [200, 201] else 'Already exists or failed' }})"
          - "Location ID: {{ private_location_id | default('Not available') }}"
          - "Enrollment Token: Created"
          - "Kubernetes Secret: synthetic-monitor-config (elastic-system namespace)"
          - "ArgoCD Application: elastic-synthetic-monitor (deployed to elastic-system)"
          - "Fleet Server URL: {{ fleet_server_default_url }}"