- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  tasks:
    - name: Deploy Elastic Operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: elastic-operator
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: eck-operator
              repoURL: https://helm.elastic.co
              targetRevision: 3.0.0
              helm:
                releaseName: elastic-operator
            destination:
              server: https://kubernetes.default.svc
              namespace: elastic-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      tags: operator

    - name: Deploy Elasticsearch
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: quickstart
            namespace: elastic-system
          spec:
            version: 8.16.1
            nodeSets:
            - name: default
              count: 1
              config:
                node.store.allow_mmap: false
              podTemplate:
                spec:
                  containers:
                  - name: elasticsearch
                    resources:
                      requests:
                        memory: 2Gi
                        cpu: 2
                      limits:
                        memory: 4Gi
                        cpu: 4
      tags: es
      register: previous_task_result

    - name: Wait for Elasticsearch pod to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: elastic-system
        label_selectors:
          - "elasticsearch.k8s.elastic.co/cluster-name=quickstart"
      register: es_pod
      until: 
        - es_pod.resources is defined 
        - es_pod.resources | length > 0 
        - es_pod.resources[0].status.phase == "Running"
        - es_pod.resources[0].status.containerStatuses is defined
        - es_pod.resources[0].status.containerStatuses | selectattr('ready') | list | length > 0
      retries: 15
      delay: 20

    - name: Deploy Kibana
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kibana.k8s.elastic.co/v1
          kind: Kibana
          metadata:
            name: quickstart
            namespace: elastic-system
          spec:
            config:
              server.publicBaseUrl: "{{ kibana_publicBaseUrl }}"
            version: 8.16.1
            count: 1
            elasticsearchRef:
              name: quickstart
      tags: kibana

    - name: Wait for Kibana pod to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: elastic-system
        label_selectors:
          - "kibana.k8s.elastic.co/name=quickstart"
      register: kb_pod
      until: 
        - kb_pod.resources is defined 
        - kb_pod.resources | length > 0 
        - kb_pod.resources[0].status.phase == "Running"
        - kb_pod.resources[0].status.containerStatuses is defined
        - kb_pod.resources[0].status.containerStatuses | selectattr('ready') | list | length > 0
      retries: 20
      delay: 30

    - name: Get Elasticsearch password
      kubernetes.core.k8s_info:
        kind: Secret
        name: quickstart-es-elastic-user
        namespace: elastic-system
      register: es_secret
      tags: get-elastic-password

    - name: Set password fact
      set_fact:
        elastic_password: "{{ es_secret.resources[0].data.elastic | b64decode }}"
      tags: get-elastic-password
  
    - name: Display Elasticsearch access information
      ansible.builtin.debug:
        msg:
          - "----------------------------------------"
          - "🚀 Elasticsearch stack deployed successfully!"
          - "----------------------------------------"
          - "📍 Elasticsearch URL: https://quickstart-es-http.elastic-system:9200"
          - "📍 Kibana URL: http://quickstart-kb-http.elastic-system:5601"
          - "👤 Username: elastic"
          - "🔑 Password: {{ elastic_password }}"
          - "----------------------------------------"
      tags: get-elastic-password
