---
- name: External Snapshotter Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: external-snapshotter
  tasks:
    - name: Deploy external-snapshotter
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: external-snapshotter
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/external-snapshotter/overlays/prod
              targetRevision: HEAD
              kustomize:
                patches:
                  - target:
                      kind: Deployment
                      name: snapshot-controller
                    patch: |-
                      - op: replace
                        path: /spec/template/spec/containers/0/image
                        value: registry.local.jazziro.com/registry-k8s-io/sig-storage/snapshot-controller:v8.4.0
                      - op: add
                        path: /spec/template/spec/imagePullSecrets
                        value:
                          - name: nexus-registry-creds
                  - target:
                      kind: Deployment
                      name: snapshot-controller
                    patch: |-
                      - op: replace
                        path: /spec/replicas
                        value: 1
            destination:
              server: https://kubernetes.default.svc
              namespace: external-snapshotter
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
            # ignoreDifferences:
            # - group: ""
            #   kind: PersistentVolumeClaim
            #   jsonPointers:
            #   - /status  # Ignore PVC status changes
