- hosts: k8s-control-plane-1
  gather_facts: no 
  become: no
  tasks:

    - name: Install Traefik CRDs
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml

    - name: Create cloudflare-api-key secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudflare-api-key
            namespace: external-dns
          type: Opaque
          stringData:
            apiToken: "{{ cloudflare_api_token }}"
      tags: external-dns

    - name: Deploy external-dns
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: external-dns
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://kubernetes-sigs.github.io/external-dns/
              chart: external-dns
              targetRevision: 1.18.0
              helm:
                values: |
                  domainFilters:
                    - {{ domain_name_filter }}
                  provider:
                    name: cloudflare
                  env:
                    - name: CF_API_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: cloudflare-api-key
                          key: apiToken
                  sources:
                  - service
                  - ingress
                  - traefik-proxy
                  extraArgs:
                  - --traefik-disable-legacy
                  # - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
                  # - --dns01-recursive-nameservers-only
                  podDnsPolicy: None
                  podDnsConfig:
                    nameservers:
                      - 1.1.1.1
                      - 9.9.9.9
            destination:
              server: https://kubernetes.default.svc
              namespace: external-dns
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true
      tags: external-dns