---
- name: Gateway API Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: gateway-infra
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ target_namespace }}"

    - name: Create public wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: "{{ certificate_ref }}" # jazziro-com-tls
            namespace: "{{ target_namespace }}"
          spec:
            secretName: "{{ certificate_ref }}" # jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ public_dns_wildcard }}"
            dnsNames:
              - "{{ public_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: "{{ local_certificate_ref }}" # local-jazziro-com-tls
            namespace: "{{ target_namespace }}"
          spec:
            secretName: "{{ local_certificate_ref }}" # local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ local_dns_wildcard }}"
            dnsNames:
              - "{{ local_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Create public wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: "{{ certificate_ref }}" # jazziro-com-tls
            namespace: "{{ target_namespace }}"
          spec:
            secretName: "{{ certificate_ref }}" # jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ public_dns_wildcard }}"
            dnsNames:
              - "{{ public_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Deploy GatewayApi local
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: Gateway
          metadata:
            name: local-gateway
            namespace: "{{ target_namespace }}"
          spec:
            gatewayClassName: traefik
            listeners:
              - name: web
                hostname: "{{ local_dns_wildcard }}"
                port: "{{ traefik_web_port }}" # 8000
                protocol: HTTP
                allowedRoutes:
                  namespaces:
                    from: All
              - name: web-public
                hostname: "{{ public_dns_wildcard }}"
                port: "{{ traefik_web_port }}" # 8000
                protocol: HTTP
                allowedRoutes:
                  namespaces:
                    from: All
              - name: websecure
                hostname: "{{ local_dns_wildcard }}"
                port: "{{ traefik_websecure_port }}" # 8443
                protocol: HTTPS
                allowedRoutes:
                  namespaces:
                    from: All
                tls:
                  mode: Terminate
                  certificateRefs:
                    - name: "{{ local_certificate_ref }}"
              - name: websecure-public
                hostname: "{{ public_dns_wildcard }}"
                port: "{{ traefik_websecure_port }}" # 8443
                protocol: HTTPS
                allowedRoutes:
                  namespaces:
                    from: All
                tls:
                  mode: Terminate
                  certificateRefs:
                    - name: "{{ certificate_ref }}"
