- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  vars:
    target_namespace: harbor
  tasks:

    - name: Create Harbor Namespace
      kubernetes.core.k8s:
        name: "{{ target_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create Harbor S3 Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: harbor-s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            REGISTRY_STORAGE_S3_ACCESSKEY: "Tv58blS9PLk6sCNf1JGB"
            REGISTRY_STORAGE_S3_SECRETKEY: "kbWY9P2u5KTGMhc473qyHozIitrjZsUpN6LvREgV"

    - name: Create Harbor Admin Password Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: harbor-admin-password
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            password: "Harbor@homelab"

    - name: Create Harbor Secret Key
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: harbor-secret-key
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            secretKey: "1234567890123456" # Must be exactly 16 characters

    - name: Deploy Harbor
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: harbor
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            sources:
              - repoURL: https://helm.goharbor.io
                chart: harbor
                targetRevision: 1.18.2
                helm:
                  releaseName: harbor
                  values: |
                    externalURL: https://{{ harbor_domain }}
                    expose:
                      type: ingress
                      tls:
                        enabled: false
                      ingress:
                        hosts:
                          core: {{ harbor_domain }}
                        className: traefik
                        annotations:
                          ingress.kubernetes.io/ssl-redirect: "true"
                          ingress.kubernetes.io/proxy-body-size: "0"
                          traefik.ingress.kubernetes.io/router.entrypoints: websecure
                          external-dns.alpha.kubernetes.io/target: "{{ traefik_service_ip }}"
                        tls:
                          - secretName: jazziro-com-tls
                            hosts:
                              - {{ harbor_domain }}
                    database:
                      type: internal
                      internal:
                        password: "Harbor12345!"
                    redis:
                      type: internal
                    persistence:
                      enabled: true
                      resourcePolicy: "keep"
                      persistentVolumeClaim:
                        database:
                          storageClass: "nfs-csi"
                          size: 5Gi
                        redis:
                          storageClass: "nfs-csi"
                          size: 2Gi
                        trivy:
                          storageClass: "nfs-csi"
                          size: 5Gi
                      imageChartStorage:
                        type: s3
                        s3:
                          region: joburg-north-1
                          bucket: harbor
                          existingSecret: harbor-s3-creds
                          regionendpoint: https://s3.local.jazziro.com
                          secure: true
                          v4auth: true
                          chunksize: "5242880"
                    existingSecretAdminPassword: "harbor-admin-password"
                    existingSecretAdminPasswordKey: "password"
                    existingSecretSecretKey: "harbor-secret-key"
                    metrics:
                      enabled: true
                      serviceMonitor:
                        enabled: true
                    trivy:
                      enabled: true
                      resources:
                        requests:
                          cpu: 200m
                          memory: 512Mi
                        limits:
                          cpu: 1
                          memory: 1Gi
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true

    - name: Create public wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: jazziro-com-tls
            namespace: "{{ target_namespace }}"
          spec:
            secretName: jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ public_dns_wildcard }}"
            dnsNames:
            - "{{ public_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com-tls
            namespace: "{{ target_namespace }}"
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ local_dns_wildcard }}"
            dnsNames:
            - "{{ local_dns_wildcard }}"
      tags:
        - ingress
        - certificate