---
- name: Headlamp Playbook
  hosts: k8s-control-plane-1
  become: false
  vars:
    target_namespace: headlamp
  tasks:
    - name: Deploy Headlamp
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: headlamp
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            sources:
              - repoURL: https://kubernetes-sigs.github.io/headlamp/
                chart: headlamp
                targetRevision: "0.41.0"
                helm:
                  releaseName: headlamp
                  valueFiles:
                    - $values/helm/headlamp_values.yaml
              - repoURL: "https://github.com/codesenju/kubelab.git"
                targetRevision: main
                ref: values
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
      tags: argocd
