---
- name: Immich Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: immich
  tasks:
    - name: Deploy postgres
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubelab.io/v1beta1
          kind: PGCluster
          metadata:
            name: immich
            namespace: "{{ target_namespace }}"
          spec:
            name: immich
            # db version must be compatiable with the backup db version
            # using tensorchord image that comes with vchord
            image: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
            sharedLibraries:
              - vectors.so
            db:
              name: immich
              username: "{{ immich_db_username }}"
              secretName: immich-postgres-secrets
              # size: 1Gi
              storageClassName: nfs-csi-postgres
            bootstrap:
              mode: recovery
            recovery:
              backupID: "20260401T020004" # backup will be at s3Path/serverName/base/<backupID>
              serverName: "immich-postgres" # backup files will be at s3Path/serverName/base
            restoreSource:
              s3Path: "s3://cnpg/backups/immich-postgres"
              endpointURL: "https://{{ rustfs_endpoint }}"
              s3:
                credentialsSecretName: s3-creds
                accessKeyId: ACCESS_KEY_ID
                secretAccessKey: SECRET_ACCESS_KEY
            archiveDestination:
              s3Path: "s3://cnpg/backup2/"
              endpointURL: "https://{{ rustfs_endpoint }}"
              # retentionPolicy: "5d"
              s3:
                credentialsSecretName: s3-creds
                accessKeyId: ACCESS_KEY_ID
                secretAccessKey: SECRET_ACCESS_KEY
            scheduledBackup:
              enabled: true
              # cron: "0 0 2 * * *"
      tags:
        - postgres

    - name: Create postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            ACCESS_KEY_ID: "{{ rustfs_access_key }}"
            SECRET_ACCESS_KEY: "{{ rustfs_secret_key }}"
      tags:
        - postgres

    - name: Create immich postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: immich-postgres-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ immich_db_username }}"
            password: "{{ immich_db_password }}"
      tags:
        - postgres

    - name: Create immich secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: immich-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            DB_HOSTNAME: "immich-postgres-rw"
            DB_USERNAME: "{{ immich_db_username }}"
            DB_PASSWORD: "{{ immich_db_password }}"
            DB_DATABASE_NAME: "{{ immich_db_name }}"
            # GOOGLE_CLIENT_ID: '{{ google_client_id }}'
            # GOOGLE_CLIENT_SECRET: '{{ google_client_secret }}'
            # MOBILE_REDIRECT_URI: '{{ mobile_redirect_uri }}'

    - name: Create immich pv
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: immich-data
            labels:
              service: immich-data # This matches the PVC selector
          spec:
            capacity:
              storage: 250Gi
            nfs:
              server: 192.168.0.16 # change me
              path: /mnt/pool2/immich/
            accessModes:
              - ReadWriteOnce
            mountOptions:
              - noatime
              - nfsvers=4.2

    - name: Create immich pvc
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: immich-data-claim
            namespace: "{{ target_namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 250Gi
            selector:
              matchLabels:
                service: immich-data # Add selector to match PV label
            volumeName: immich-data
            storageClassName: "" # This prevents dynamic provisioning

    - name: Create immich cache pv
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: immich-cache
            labels:
              service: immich-cache # This matches the PVC selector
          spec:
            capacity:
              storage: 250Gi
            nfs:
              server: 192.168.0.16 # change me
              path: /mnt/pool2/immich/
            accessModes:
              - ReadWriteOnce
            mountOptions:
              - noatime
              - nfsvers=4.2

    - name: Create immich pvc
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: immich-cache-claim
            namespace: "{{ target_namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 250Gi
            selector:
              matchLabels:
                service: immich-cache # Add selector to match PV label
            volumeName: immich-cache
            storageClassName: "" # This prevents dynamic provisioning

    - name: Deploy immich
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: immich
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            sources:
              - repoURL: ghcr.io/immich-app/immich-charts
                chart: immich
                targetRevision: "0.10.3"
                helm:
                  releaseName: immich
                  valueFiles:
                    - $values/helm/immich_values.yaml
              - repoURL: "https://github.com/codesenju/kubelab.git"
                targetRevision: main
                ref: values
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Create HTTPRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: immich
            namespace: "{{ target_namespace }}"
          spec:
            hostnames:
              - "photos.{{ public_dns }}"
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: websecure-public
            rules:
              - backendRefs:
                  - name: immich-server
                    port: 2283
