- hosts: k8s-control-plane-1
  become: no
  vars:
    ingress_nginx_load_balancer_ip: 192.168.0.61
  tasks:

    - name: Deploy ingress-nginx
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ingress-nginx
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: ingress-nginx
              repoURL: https://kubernetes.github.io/ingress-nginx
              targetRevision: 4.13.0
              helm:
                releaseName: ingress-nginx
                values: |
                  controller:
                    service:
                      loadBalancerIP: "{{ ingress_nginx_load_balancer_ip }}"
            destination:
              server: https://kubernetes.default.svc
              namespace: ingress-nginx
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
