---
- name: Npm Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: n8n
  tasks:
    - name: Deploy instagram-reels-downloader
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: instagram-reels-downloader
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/instagram-reels-downloader/overlays/prod
              targetRevision: main
              kustomize:
                images:
                  - IMAGE_TEMPLATE={{ registry_domain }}/kubelab/instagram-reels-downloader:v2
                commonLabels:
                  app.kubernetes.io/instance: instagram-reels-downloader
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
