- hosts: k8s-control-plane-1
  become: no
  tasks:

    - name: Deploy Jellyfin
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: jellyfin
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/jellyfin/overlays/production
              targetRevision: development
              kustomize:
                # Add these to your existing kustomize config
                commonAnnotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                commonLabels:
                  app.kubernetes.io/instance: jellyfin-prod
          
            destination:
              server: https://kubernetes.default.svc
              namespace: jellyfin
          
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true

            # ignoreDifferences:
            # - group: ""
            #   kind: PersistentVolumeClaim
            #   jsonPointers:
            #   - /status  # Ignore PVC status changes
      tags: jellyfin
