---
- name: Kro RGD
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: kro
  tasks:
    - name: Deploy Kro RGD's
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: kro-rgd
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/kro-rgd/overlays/prod
              targetRevision: main
              kustomize:
                # Add these to your existing kustomize config
                commonAnnotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                commonLabels:
                  app.kubernetes.io/instance: kro-rgd
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
