---
- name: Kro Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: kro
  tasks:
    - name: Deploy Kro
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: kro
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: registry.k8s.io/kro/charts # oci chart
              chart: kro
              targetRevision: 0.9.0
              helm:
                releaseName: kro
                values: |
                  image:
                    repository: registry.k8s.io/kro/kro
                    # tag: "v0.9.0"
                  deployment:
                    resources:
                      requests:
                        cpu: 60m
                        memory: 64Mi
                      limits:
                        cpu: 250m
                        memory: 256Mi
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
            # ignoreDifferences:
            #   - group: "postgresql.cnpg.io"
            #     kind: Cluster
            #     jsonPointers:
            #       - /spec/managed/roles
