- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  tasks:

    - name: Deploy Kube Prometheus Stack
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: kube-prometheus-stack
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            sources:
            - repoURL: https://prometheus-community.github.io/helm-charts
              chart: kube-prometheus-stack
              targetRevision: "75.13.0"
              helm:
                releaseName: kube-prometheus-stack
                valueFiles:
                - $values/helm/kube_prometheus_stack_values.yaml
            - repoURL: 'https://github.com/codesenju/kubelab.git'
              targetRevision: main
              ref: values
            destination:
              server: https://kubernetes.default.svc
              namespace: kube-prometheus-stack
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true

            # ignoreDifferences:
            # - group: ""
            #   kind: PersistentVolumeClaim
            #   jsonPointers:
            #   - /status  # Ignore PVC status changes
      tags: kube-prometheus-stack

    - name: Create Thanos S3 Secret (inline YAML, using stringData)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: thanos-s3
            namespace: kube-prometheus-stack
          type: Opaque
          stringData:
            objstore.yaml: |
              type: s3
              config:
                bucket: thanos-store
                endpoint: {{ minio_endpoint }}
                access_key: {{ s3_access_key }}
                secret_key: {{ s3_secret_key }}
                insecure: true
      tags: kube-prometheus-stack

    - name: Wait for Grafana pod to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: kube-prometheus-stack
        label_selectors:
          - app.kubernetes.io/name=grafana
      register: grafana_pod
      until: grafana_pod.resources | length > 0 and grafana_pod.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    - name: Get Grafana admin password
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: kube-prometheus-stack-grafana
        namespace: kube-prometheus-stack
      register: grafana_secret

    - name: Display Grafana login credentials
      ansible.builtin.debug:
        msg: >
          Grafana Login Credentials:
          URL: http://localhost:3000 (after port-forward)
          Username: "{{ grafana_secret.resources[0].data['admin-user'] | b64decode }}"
          Password: "{{ grafana_secret.resources[0].data['admin-password'] | b64decode }}"