- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  vars:
    namespace: media-stack
  tasks:

    - name: Deploy Media Stack
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: media-stack
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/media-stack/overlays/production
              targetRevision: main
              kustomize:
                # Add these to your existing kustomize config
                commonAnnotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                commonLabels:
                  app.kubernetes.io/instance: media-stack-prod
          
            destination:
              server: https://kubernetes.default.svc
              namespace: media-stack
          
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true

            # ignoreDifferences:
            # - group: ""
            #   kind: PersistentVolumeClaim
            #   jsonPointers:
            #   - /status  # Ignore PVC status changes
      tags: media-stack

    - name: Create public wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: jazziro-com-tls
            namespace: media-stack
          spec:
            secretName: jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ public_dns_wildcard }}"
            dnsNames:
            - "{{ public_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com-tls
            namespace: media-stack
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ local_dns_wildcard }}"
            dnsNames:
            - "{{ local_dns_wildcard }}"
      tags:
        - ingress
        - certificate

    - name: Create flaresolverr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: flaresolverr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "flaresolverr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "flaresolverr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: flaresolverr
                          port:
                            number: 8191
      tags:
        - ingress

    - name: Create lidarr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: lidarr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "lidarr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "lidarr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: lidarr
                          port:
                            number: 8686
      tags:
        - ingress

    - name: Create prowlarr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: prowlarr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "prowlarr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "prowlarr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: prowlarr
                          port:
                            number: 9696
      tags:
        - ingress

    - name: Create tdarr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: tdarr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "tdarr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "tdarr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: tdarr
                          port:
                            number: 8265
      tags:
        - ingress

    - name: Create Jellyfin Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: jellyfin
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "stream.{{ public_dns }}"
                secretName: jazziro-com-tls
              - hosts:
                  - "stream.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "stream.{{ public_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: jellyfin
                          port:
                            number: 8096
              - host: "stream.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: jellyfin
                          port:
                            number: 8096
      tags:
        - ingress

# Ingress exposing Jellyseer to the public internet via Traefik
    - name: Create Jellyseer Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: jellyseer
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "catalog.{{ public_dns }}"
                secretName: jazziro-com-tls
              - hosts:
                  - "catalog.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "catalog.{{ public_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: jellyseerr
                          port:
                            number: 5055
              - host: "catalog.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: jellyseerr
                          port:
                            number: 5055
      tags:
        - ingress

    - name: Create sonarr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: sonarr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "sonarr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "sonarr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: sonarr
                          port:
                            number: 8989
      tags:
        - ingress

    - name: Create radarr Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: radarr
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "radarr.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "radarr.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: radarr
                          port:
                            number: 7878
      tags:
        - ingress

    - name: Create jackett Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: jackett
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
              - hosts:
                  - "jackett.{{ local_dns }}"
                secretName: local-jazziro-com-tls
            rules:
              - host: "jackett.{{ local_dns }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: jackett
                          port:
                            number: 9117
      tags:
        - ingress