- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  tasks:

    - name: Deploy Metrics Server
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: metrics-server
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: metrics-server
              repoURL: https://kubernetes-sigs.github.io/metrics-server/
              targetRevision: 3.12.2
              helm:
                releaseName: metrics-server
                values: |
                  args:
                    - --kubelet-insecure-tls
            destination:
              server: https://kubernetes.default.svc
              namespace: metrics-server
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true