---
- hosts: k8s-control-plane-1
  gather_facts: no
  tasks:
    - name: Deploy minio
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: minio
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/minio/overlays/prod
              targetRevision: main
              kustomize:
                labels:
                  app.kubernetes.io/instance: minio
            destination:
              server: https://kubernetes.default.svc
              namespace: minio
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
              - RespectIgnoreDifferences=true
     