---
- name: Nexus Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  vars:
    target_namespace: nexus
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ target_namespace }}"

    - name: Create nexus postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: nexus-postgres-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ nexus_db_username }}"
            password: "{{ nexus_db_password }}"
      tags:
        - postgres

    - name: Create postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            ACCESS_KEY_ID: "{{ rustfs_access_key }}"
            SECRET_ACCESS_KEY: "{{ rustfs_secret_key }}"
      tags:
        - postgres

    - name: Deploy postgres
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubelab.io/v1beta1
          kind: PGCluster
          metadata:
            name: nexus
            namespace: "{{ target_namespace }}"
          spec:
            name: nexus
            # db version must be compatiable with the backup db version
            # using tensorchord image that comes with vchord
            # image: ghcr.io/cloudnative-pg/postgresql:16-standard-trixie
            db:
              name: nexus
              username: "{{ nexus_db_username }}"
              secretName: nexus-postgres-secrets
              # size: 1Gi
              storageClassName: nfs-csi-postgres
            bootstrap:
              mode: recovery
            recovery:
              backupID: "20260403T193212" # backup will be at s3Path/serverName/base/<backupID>
              serverName: "nexus-postgres" # backup files will be at s3Path/serverName/base
            restoreSource:
              s3Path: "s3://cnpg/backups/nexus"
              endpointURL: "https://{{ rustfs_endpoint }}"
              s3:
                credentialsSecretName: s3-creds
                accessKeyId: ACCESS_KEY_ID
                secretAccessKey: SECRET_ACCESS_KEY
            archiveDestination:
              s3Path: "s3://cnpg/backup2"
              endpointURL: "https://{{ rustfs_endpoint }}"
              # retentionPolicy: "5d"
              s3:
                credentialsSecretName: s3-creds
                accessKeyId: ACCESS_KEY_ID
                secretAccessKey: SECRET_ACCESS_KEY
            scheduledBackup:
              enabled: true
              # cron: "0 0 2 * * *"
      tags:
        - postgres

    - name: Deploy nexus
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: nexus
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/nexus/overlays/prod
              targetRevision: main
              kustomize:
                # Add these to your existing kustomize config
                labels:
                  app.kubernetes.io/instance: nexus
                patches:
                  - target:
                      group: gateway.networking.k8s.io
                      version: v1
                      kind: HTTPRoute
                      name: nexus-repo
                    patch: |-
                      - op: replace
                        path: /spec/hostnames
                        value:
                          - "nexus.{{ local_dns }}"
                          - "registry.{{ local_dns }}"
                          - "nexus.{{ public_dns }}"
                          - "registry.{{ public_dns }}"
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
            ignoreDifferences:
              - group: "gateway.networking.k8s.io"
                kind: HTTPRoute
                name: nexus-repo
                jqPathExpressions:
                  - .spec.parentRefs[]
                  - .spec.rules[]
