- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  vars:
    namespace: opentelemetry-operator-system
  tasks:
    - name: Create ArgoCD Application for OpenTelemetry Operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: opentelemetry
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: 'https://github.com/codesenju/kubelab.git'
              targetRevision: HEAD
              path: kustomize/opentelemetry/overlays/prod
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{ namespace }}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Create OpenTelemetryCollector resource
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: opentelemetry.io/v1alpha1
          kind: OpenTelemetryCollector
          metadata:
            name: signoz-otel
            namespace: '{{ namespace }}'
          spec:
            mode: deployment
            config: |
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: 0.0.0.0:4317
                    http:
                      endpoint: 0.0.0.0:4318
              processors:
                batch: {}
                resource/env:
                  attributes:
                  - key: deployment.environment
                    value: prod # can be dev, prod, staging etc. based on your environment
                    action: upsert
              exporters:
                debug:
                  verbosity: detailed
                otlp:
                  endpoint: "{{ signoz_otel_endpoint }}" # replace <region> with your region of SigNoz Cloud
                  tls:
                    insecure: false
                  # headers:
                  #   "signoz-ingestion-key": "<your-ingestion-key>" # Obtain from https://{your-signoz-tenant-url}/settings/ingestion-settings
              service:
                pipelines:
                  traces:
                    receivers: [otlp]
                    processors: [batch2, resource/env]
                    exporters: [otlp,debug]

    - name: Create Instrumentation resource for nodejs-instrumentation
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: opentelemetry.io/v1alpha1
          kind: Instrumentation
          metadata:
            name: traces-instrumentation
            namespace: media-stack
          spec:
            exporter:
              endpoint: "{{ signoz_otel_endpoint }}"
              # endpoint:  http://signoz-otel-collector.opentelemetry-operator-system.svc.cluster.local:4317
            env:
              # - name: OTEL_EXPORTER_OTLP_HEADERS
              #   value: signoz-ingestion-key="<signoz-token>"  # Obtain from https://{your-signoz-url}/settings/ingestion-settings
              - name: OTEL_EXPORTER_OTLP_INSECURE
                value: "false"
              - name: OTEL_RESOURCE_ATTRIBUTES
                value: "deployment.environment=prod" # can be dev, prod, staging etc. based on your environment 
            propagators:
              - tracecontext
              - baggage
              - b3
            sampler:
              type: parentbased_traceidratio
              argument: "1"
            nodejs:
              image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
