- hosts: k8s-control-plane-1
  gather_facts: no
  become: no
  tasks:

    - name: Create Elastic secret for OpenTelemetry
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: elastic-secret-otel
            namespace: opentelemetry-operator-system
          type: Opaque
          stringData:
            elastic_endpoint: "{{ elastic_endpoint }}"
            elastic_api_key: "{{ elastic_api_key }}"
      tags: secret

    - name: Deploy OpenTelemetry ArgoCD Application
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: opentelemetry-operator
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            sources:
            - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
              chart: opentelemetry-kube-stack
              targetRevision: "0.6.3"
              helm:
                releaseName: opentelemetry-kube-stack
                valueFiles:
                - $values/helm/otel_operator_values.yaml
            - repoURL: 'https://github.com/codesenju/kubelab.git'
              targetRevision: main
              ref: values
            destination:
              server: https://kubernetes.default.svc
              namespace: opentelemetry-operator-system
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              - ServerSideApply=true
      tags: opentelemetry-operator