- hosts: k8s-control-plane-1
  become: no
  tasks:

    - name: Deploy Signoz
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: signoz
              repoURL: https://charts.signoz.io
              targetRevision: 0.76.1
              helm:
                releaseName: signoz
                values: |
                  global:
                    storageClass: nfs-csi
                    clusterName: "kubelab"
                    clickhouse:
                      installCustomStorageClass: true
            destination:
              server: https://kubernetes.default.svc
              namespace: monitoring
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Deploy Signoz k8s-infra
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz-k8s-infra
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: k8s-infra
              repoURL: https://charts.signoz.io
              targetRevision: 0.12.1
              helm:
                releaseName: signoz-k8s-infra
                values: |
                  global:
                    cloud: others
                    clusterName: "kubelab"
                    storageClass: "nfs-csi"
                    clickhouse:
                     installCustomStorageClass: true
                    deploymentEnvironment: prod
                  otelCollectorEndpoint: signoz-otel-collector.monitoring.svc.cluster.local:4317
                  otelInsecure: true
                  presets:
                    otlpExporter:
                      enabled: true
                    hostMetrics:
                      enabled: true
                      collectionInterval: 30s
                    logsCollection:
                      enabled: true
                    kubeletMetrics:
                      enabled: true
                    kubernetesAttributes:
                      enabled: true
                    loggingExporter:
                      enabled: true
            destination:
              server: https://kubernetes.default.svc
              namespace: monitoring
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true