- hosts: k8s-control-plane-1
  become: no
  gather_facts: no
  vars:
    namespace: signoz
  tasks:

    - name: Create Docker pull secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-secret
            namespace: '{{ namespace }}'
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ {'auths': {'https://index.docker.io/v1/': {'username': docker_username, 'password': docker_password, 'auth': (docker_username + ':' + docker_password) | b64encode}}} | to_json | b64encode }}"

    - name: Deploy Signoz
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: signoz
              repoURL: https://charts.signoz.io
              targetRevision: 0.103.0
              helm:
                releaseName: signoz
                values: |
                  global:
                    storageClass: nfs-csi
                    clusterName: kubelab
                  imagePullSecrets:
                    - dockerhub-secret
                  
                  # ClickHouse optimization
                  clickhouse:
                    installCustomStorageClass: true
                    imagePullSecrets:
                      - dockerhub-secret
                    persistence:
                      size: 50Gi
                    resources:
                      requests:
                        cpu: 2000m
                        memory: 4Gi
                      limits:
                        cpu: 4000m
                        memory: 8Gi
                    # Increase write buffer and merge settings
                    configOverride: |
                      <clickhouse>
                        <max_concurrent_queries>200</max_concurrent_queries>
                        <max_table_size_to_drop>0</max_table_size_to_drop>
                        <max_partition_size_to_drop>0</max_partition_size_to_drop>
                        <merge_tree>
                          <max_bytes_to_merge_at_max_space_in_pool>161061273600</max_bytes_to_merge_at_max_space_in_pool>
                          <parts_to_throw_insert>3000</parts_to_throw_insert>
                          <parts_to_delay_insert>1000</parts_to_delay_insert>
                        </merge_tree>
                      </clickhouse>
                  
                  # OTel Collector optimization
                  otelCollector:
                    imagePullSecrets:
                      - dockerhub-secret
                    service:
                      type: ClusterIP
                    resources:
                      requests:
                        cpu: 500m
                        memory: 1Gi
                      limits:
                        cpu: 2000m
                        memory: 4Gi
                    config:
                      exporters:
                        clickhousetraces:
                          timeout: 30s
                          sending_queue:
                            enabled: true
                            num_consumers: 20
                            queue_size: 5000
                          retry_on_failure:
                            enabled: true
                            initial_interval: 5s
                            max_interval: 30s
                            max_elapsed_time: 300s
                        clickhouselogsexporter:
                          timeout: 30s
                          sending_queue:
                            enabled: true
                            num_consumers: 20
                            queue_size: 5000
                      processors:
                        batch:
                          timeout: 5s
                          send_batch_size: 10000
                          send_batch_max_size: 20000
                  
                  signoz:
                    imagePullSecrets:
                      - dockerhub-secret
            destination:
              server: https://kubernetes.default.svc
              namespace: signoz
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      tags: signoz

    - name: Deploy Signoz k8s-infra
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz-k8s-infra
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: k8s-infra
              repoURL: https://charts.signoz.io
              targetRevision: 0.15.0
              helm:
                releaseName: signoz-k8s-infra
                values: |
                  global:
                    cloud: others
                    clusterName: "kubelab"
                    storageClass: "nfs-csi"
                    deploymentEnvironment: prod
                    imagePullSecrets:
                      - "dockerhub-secret"
                  otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
                  otelInsecure: true
                  insecureSkipVerify: true
                  otelAgent:
                    ports:
                      otlp:
                        hostPort: ""
                      otlp-http:
                        hostPort: ""
                      metrics:
                        hostPort: ""
                      health-check:
                        hostPort: ""
                  presets:
                    otlpExporter:
                      enabled: true
                    loggingExporter:
                      enabled: false
                    hostMetrics:
                      enabled: true
                      collectionInterval: 30s
                    hostPort:
                      enabled: false
                    logsCollection:
                      enabled: true
                      blacklist:
                        enabled: true
                        namespaces: 
                          - kube-system
                    kubeletMetrics:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    kubernetesAttributes:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    clusterMetrics:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    k8sEvents:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
            destination:
              server: https://kubernetes.default.svc
              namespace: signoz
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com
            namespace: '{{ namespace }}'
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ dns_name_2 }}"
            dnsNames:
            - "{{ dns_name_1 }}"
            - "{{ dns_name_2 }}"

    - name: Create signoz IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: signoz
            namespace: '{{ namespace }}'
            annotations:
              kubernetes.io/ingress.class: traefik
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`signoz.{{ dns_name_1 }}`)
                kind: Rule
                services:
                  - name: signoz
                    kind: Service
                    port: 8080
            tls:
              secretName: local-jazziro-com-tls

    - name: Create signoz-otel-collector Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: signoz-otel-collector
            namespace: '{{ namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
            - hosts:
              - "signoz-otel-collector.{{ dns_name_1 }}"
              secretName: local-jazziro-com-tls
            rules:
            - host: "signoz-otel-collector.{{ dns_name_1 }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: signoz-otel-collector
                      port:
                        number: 4318
      tags: 
      - ingress