- hosts: k8s-control-plane-1
  become: no
  gather_facts: no
  vars:
    target_namespace: signoz
  tasks:

    - name: Deploy signoz postgres
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: signoz-postgres
            namespace: "{{ target_namespace }}"
          spec:
            # At the time of writing, is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
            imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba # UID 26, GID 999
            instances: 1
            postgresql:
              shared_preload_libraries:
                - "vectors.so"
            bootstrap:
              initdb:
                database: signoz
                owner: signoz
                secret:
                  name: signoz-postgres-secrets
                postInitSQL:
                  - CREATE EXTENSION IF NOT EXISTS "vectors";
                  - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
                  - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
            storage:
              size: 1Gi
              pvcTemplate:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: "nfs-csi"
            backup:
              # 3-day retention for both base backups and WALsgit
              retentionPolicy: "3d"
              barmanObjectStore:
                destinationPath: s3://cnpg/backups
                # Only needed if NOT using AWS (e.g., MinIO or DigitalOcean)
                endpointURL: "https://{{ rustfs_endpoint }}"
                s3Credentials:
                  accessKeyId:
                    name: s3-creds
                    key: ACCESS_KEY_ID
                  secretAccessKey:
                    name: s3-creds
                    key: SECRET_ACCESS_KEY
                wal:
                  compression: gzip
                data:
                  compression: gzip
                  jobs: 2
      tags:
        - postgres
  
    - name: Create coder postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: s3-creds
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            ACCESS_KEY_ID: "{{ rustfs_access_key }}"
            SECRET_ACCESS_KEY: "{{ rustfs_secret_key }}"
      tags:
        - postgres

    - name: Create signoz postgres secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: signoz-postgres-secrets
            namespace: "{{ target_namespace }}"
          type: Opaque
          stringData:
            username: "{{ signoz_db_username }}"
            password: "{{ signoz_db_password }}"
      tags:
        - postgres

    - name: Deploy ScheduledBackup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: postgresql.cnpg.io/v1
          kind: ScheduledBackup
          metadata:
            name: daily-s3-backup
            namespace: "{{ target_namespace }}"
          spec:
            # Standard Cron: s m h dom mon dow
            # This runs every day at 2:00 AM
            schedule: "0 0 2 * * *"
            cluster:
              name: signoz-postgres
            # Setting this to true takes a backup immediately upon creation
            immediate: true
            # 'self' means this ScheduledBackup object owns the resulting Backup records
            backupOwnerReference: self
      tags:
        - postgres

    - name: Deploy Signoz
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: signoz
              repoURL: https://charts.signoz.io
              targetRevision: 0.116.2
              helm:
                releaseName: signoz
                values: |
                  signoz:
                    imagePullSecrets:
                      - dockerhub-secret
                    env:
                      signoz_telemetrystore_provider: clickhouse
                      signoz_emailing_enabled: false
                      signoz_alertmanager_provider: signoz
                      signoz_alertmanager_signoz_external__url: "{{ signoz_host }}"
                      signoz_sqlstore_proviser: postgres
                      signoz_sqlstore_postgres_dsn: "{{ signoz_sqlstore_postgres_dsn }}"
                  global:
                    storageClass: nfs-csi
                    clusterName: kubelab
                  imagePullSecrets:
                    - dockerhub-secret
                  # ClickHouse optimization
                  clickhouse:
                    initContainers:
                      udf:
                        enabled: false
                    coldStorage:
                      enabled: true
                      # Set free space size on default disk in bytes
                      defaultKeepFreeSpaceBytes: "10485760" # 10MiB
                      type: s3
                      endpoint: "https://{{ rustfs_endpoint }}/signoz/"
                      accessKey: "{{ rustfs_access_key }}"
                      secretAccess: "{{ rustfs_secret_key }}"
                    storageClass: nfs-csi
                    imagePullSecrets:
                      - dockerhub-secret
                    persistence:
                      size: 20Gi
                    resources:
                      requests:
                        cpu: 2
                        memory: 4Gi
                      limits:
                        cpu: 4
                        memory: 8Gi
                    # HA Config
                    layout:
                      shardsCount: 1 # Perfomance
                      replicasCount: 2 # HA
                    zookeeper:
                      replicaCount: 2
                    schemaMigrator:
                      enableReplication: true
                    # podDistribution:
                    #   # All instances in unique nodes:
                    #   - type: ClickHouseAntiAffinity
                    #     topologyKey: kubernetes.io/hostname
                    #   # Distribute shards of replicas across nodes:
                    #   - type: ReplicaAntiAffinity
                    #     topologyKey: kubernetes.io/hostname
                    #   # Distribute replicas of shards across nodes:
                    #   - type: ShardAntiAffinity
                    #     topologyKey: kubernetes.io/hostname
                    # Increase write buffer and merge settings
                    configOverride: |
                      <clickhouse>
                        <max_concurrent_queries>200</max_concurrent_queries>
                        <max_table_size_to_drop>0</max_table_size_to_drop>
                        <max_partition_size_to_drop>0</max_partition_size_to_drop>
                        <merge_tree>
                          <max_bytes_to_merge_at_max_space_in_pool>161061273600</max_bytes_to_merge_at_max_space_in_pool>
                          <parts_to_throw_insert>3000</parts_to_throw_insert>
                          <parts_to_delay_insert>1000</parts_to_delay_insert>
                        </merge_tree>
                      </clickhouse>
                  
                  # OTel Collector optimization
                  otelCollector:
                    imagePullSecrets:
                      - dockerhub-secret
                    service:
                      type: ClusterIP
                    resources:
                      requests:
                        cpu: 500m
                        memory: 1Gi
                      limits:
                        cpu: 1000m
                        memory: 2Gi
                    config:
                      exporters:
                        clickhousetraces:
                          timeout: 30s
                          sending_queue:
                            enabled: true
                            num_consumers: 20
                            queue_size: 5000
                          retry_on_failure:
                            enabled: true
                            initial_interval: 5s
                            max_interval: 30s
                            max_elapsed_time: 300s
                        clickhouselogsexporter:
                          timeout: 30s
                          sending_queue:
                            enabled: true
                            num_consumers: 40
                            queue_size: 15000
                      processors:
                        batch:
                          timeout: 10s
                          send_batch_size: 50000     
                          send_batch_max_size: 100000
            destination:
              server: https://kubernetes.default.svc
              namespace: signoz
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      tags:
        - argocd

    - name: Create Docker pull secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-secret
            namespace: '{{ target_namespace }}'
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ {'auths': {'https://index.docker.io/v1/': {'username': docker_username, 'password': docker_password, 'auth': (docker_username + ':' + docker_password) | b64encode}}} | to_json | b64encode }}"

    - name: Deploy Signoz k8s-infra
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: signoz-k8s-infra
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: k8s-infra
              repoURL: https://charts.signoz.io
              targetRevision: 0.15.0
              helm:
                releaseName: signoz-k8s-infra
                values: |
                  global:
                    cloud: others
                    clusterName: "kubelab"
                    storageClass: "nfs-csi"
                    deploymentEnvironment: prod
                    imagePullSecrets:
                      - "dockerhub-secret"
                  otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
                  otelInsecure: true
                  insecureSkipVerify: true
                  otelAgent:
                    ports:
                      otlp:
                        hostPort: ""
                      otlp-http:
                        hostPort: ""
                      metrics:
                        hostPort: ""
                      health-check:
                        hostPort: ""
                  presets:
                    otlpExporter:
                      enabled: true
                    loggingExporter:
                      enabled: false
                    hostMetrics:
                      enabled: true
                      collectionInterval: 30s
                    hostPort:
                      enabled: false
                    logsCollection:
                      enabled: true
                      blacklist:
                        enabled: true
                        namespaces: 
                          - kube-system
                    kubeletMetrics:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    kubernetesAttributes:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    clusterMetrics:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
                    k8sEvents:
                      enabled: true
                      otelInsecure: true
                      insecureSkipVerify: true
            destination:
              server: https://kubernetes.default.svc
              namespace: signoz
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
      tags:
        - argocd

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com
            namespace: '{{ target_namespace }}'
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ local_dns_wildcard }}"
            dnsNames:
            - "{{ local_dns }}"
            - "{{ local_dns_wildcard }}"

    - name: Create signoz IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: signoz
            namespace: '{{ target_namespace }}'
            annotations:
              kubernetes.io/ingress.class: traefik
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`signoz.{{ local_dns }}`)
                kind: Rule
                services:
                  - name: signoz
                    kind: Service
                    port: 8080
            tls:
              secretName: local-jazziro-com-tls
      tags: 
      - ingress

    - name: Create signoz-otel-collector Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: signoz-otel-collector
            namespace: '{{ target_namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
            - hosts:
              - "signoz-otel-collector.{{ local_dns }}"
              secretName: local-jazziro-com-tls
            rules:
            - host: "signoz-otel-collector.{{ local_dns }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: signoz-otel-collector
                      port:
                        number: 4318
      tags: 
      - ingress

    - name: Create signoz frontend Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: signoz
            namespace: '{{ target_namespace }}'
            annotations:
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
              # cert-manager.io/cluster-issuer: letsencrypt-production
          spec:
            ingressClassName: traefik
            tls:
            - hosts:
              - "signoz.{{ local_dns }}"
              secretName: local-jazziro-com-tls
            rules:
            - host: "signoz.{{ local_dns }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: signoz
                      port:
                        number: 8080
      tags: 
      - ingress
