- hosts: k8s-control-plane-1
  become: no
  gather_facts: no
  vars:
    nfs_server_ip: 192.168.0.15
    nfs_server_path: /mnt/pool1/AppData/stirlingpdf/
  tasks:

    - name: Deploy stirling-pdf
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: stirling-pdf
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: stirling-pdf-chart
              repoURL: https://docs.stirlingpdf.com/Stirling-PDF-chart
              targetRevision: 1.9.1
              helm:
                releaseName: stirling-pdf
                values: |
                  persistence:
                    enabled: true
                    accessMode: ReadWriteOnce
                    size: 8Gi
                    labels:
                      {}
                      # name: value
                    path: /tmp
                    pv:
                      enabled: true
                      pvname: "stirning-pdf-data"
                      capacity:
                        storage: 8Gi
                      accessMode: ReadWriteOnce
                      nfs:
                        server: {{ nfs_server_ip  }}
                        path: {{ nfs_server_path }}
            destination:
              server: https://kubernetes.default.svc
              namespace: pdf
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Create local wildcar certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: local-jazziro-com
            namespace: pdf
          spec:
            secretName: local-jazziro-com-tls
            issuerRef:
              name: letsencrypt-production
              kind: ClusterIssuer
            commonName: "{{ dns_name_2 }}"
            dnsNames:
            - "{{ dns_name_1 }}"
            - "{{ dns_name_2 }}"

    - name: Create Traefik dashboard IngressRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: IngressRoute
          metadata:
            name: stirling-pdf
            namespace: pdf
            annotations:
              kubernetes.io/ingress.class: traefik
              external-dns.alpha.kubernetes.io/target: '{{ traefik_service_ip }}'
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`pdf.{{ dns_name_1 }}`)
                kind: Rule
                services:
                  - name: stirling-pdf-stirling-pdf-chart
                    kind: Service
                    namespace: pdf
                    port: 8080
            tls:
              secretName: local-jazziro-com-tls