- name: Stirling pdf Playbook
  hosts: k8s-control-plane-1
  become: false
  gather_facts: false
  vars:
    nfs_server_ip: 192.168.0.16
    nfs_server_path: /mnt/pool2/AppData/stirlingpdf/
    target_namespace: pdf
  tasks:

    - name: Deploy stirling-pdf
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: stirling-pdf
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              chart: stirling-pdf-chart
              repoURL: https://docs.stirlingpdf.com/Stirling-PDF-chart
              targetRevision: 3.1.0
              helm:
                releaseName: stirling-pdf
                values: |
                  probes:
                    liveness:
                      enabled: false
                  persistence:
                    enabled: true
                    accessMode: ReadWriteOnce
                    size: 2Gi
                    labels:
                      {}
                      # name: value
                    path: /tmp
                    pv:
                      enabled: true
                      pvname: "stirling-pdf-data"
                      capacity:
                        storage: 2Gi
                      accessMode: ReadWriteOnce
                      nfs:
                        server: {{ nfs_server_ip  }}
                        path: {{ nfs_server_path }}
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true

    - name: Create n8n HTTPRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: pdf
            namespace: "{{ target_namespace }}"
          spec:
            hostnames:
              - "pdf.{{ local_dns }}"
            parentRefs:
              - name: local-gateway
                namespace: gateway-infra
                sectionName: websecure
            rules:
              - backendRefs:
                  - name: stirling-pdf-stirling-pdf-chart
                    port: 8080
      tags:
        - ingress
