---
- name: Uptime-kuma Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: uptime-kuma
  tasks:
    - name: Deploy uptime-kuma ArgoCD Application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: uptime-kuma
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://github.com/codesenju/kubelab.git
              path: kustomize/uptime-kuma/overlays/prod
              targetRevision: main
              kustomize:
                images:
                  - IMAGE_TEMPLATE=louislam/uptime-kuma:2.5.3
                commonAnnotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                commonLabels:
                  app.kubernetes.io/instance: uptime-kuma-prod
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - RespectIgnoreDifferences=true
      tags:
        - argocd

    - name: Create uptime-kuma HTTPRoute
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: uptime-kuma
            namespace: "{{ target_namespace }}"
          spec:
            parentRefs:
              - name: local-gateway
                namespace: "{{ gatewayapi_namespace }}"
                sectionName: websecure
            hostnames:
              - "uptime.{{ public_dns }}"
            rules:
              - backendRefs:
                  - name: uptime-kuma
                    port: 3000
      tags:
        - httproute
      when: false

    - name: Create uptime-kuma HTTP to HTTPS redirect
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: uptime-kuma-redirect
            namespace: "{{ target_namespace }}"
          spec:
            parentRefs:
              - name: local-gateway
                namespace: "{{ gatewayapi_namespace }}"
                sectionName: web
            hostnames:
              - "uptime.{{ public_dns }}"
            rules:
              - filters:
                  - type: RequestRedirect
                    requestRedirect:
                      scheme: https
                      statusCode: 301
                      port: 443
      tags:
        - httproute
      when: false
