---
- name: VPA Playbook
  hosts: k8s-control-plane-1
  gather_facts: false
  become: false
  vars:
    target_namespace: autoscalers
  tasks:
    - name: Deploy VPA
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: vertical-pod-autoscaler
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            source:
              repoURL: https://kubernetes.github.io/autoscaler
              chart: vertical-pod-autoscaler
              targetRevision: 0.8.1
              helm:
                releaseName: vertical-pod-autoscaler
                values: |
                  imagePullSecrets:
                    - name: "nexus-registry-creds"
                  admissionController:
                    image:
                      repository:  "registry.local.jazziro.com/registry-k8s-io/autoscaling/vpa-admission-controller"
                  certGen:
                    image:
                      repository: "registry.local.jazziro.com/registry-k8s-io/ingress-nginx/kube-webhook-certgen"
                  recommender:
                    image:
                      repository: "registry.local.jazziro.com/registry-k8s-io/autoscaling/vpa-recommender"
                  updater:
                    image:
                      repository: "registry.local.jazziro.com/registry-k8s-io/autoscaling/vpa-updater"
            destination:
              server: https://kubernetes.default.svc
              namespace: "{{ target_namespace }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
