apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  labels:
    app.kubernetes.io/component: book-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
        app.kubernetes.io/component: book-management
    spec:
      securityContext:
        fsGroup: 1000  # Matches shared PGID
      containers:
      - name: readarr
        image: lscr.io/linuxserver/readarr:develop
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: shared-permissions
        - configMapRef:
            name: global-env
        ports:
        - containerPort: 8787
          name: http
        volumeMounts:
        - name: media-stack-config
          mountPath: /config
          subPath: readarr/config
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
      volumes:
      - name: media-stack-config
        persistentVolumeClaim:
          claimName: media-stack-config
      - name: data
        persistentVolumeClaim:
          claimName: media-data