apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app.kubernetes.io/component: book-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8787
    targetPort: 8787
  selector:
    app: readarr