apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-postgres
spec:
  # At the time of writing, coder is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba # UID 26, GID 999
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    roles:
      - name: coder
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-postgres-secrets
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  storage:
    size: 5Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: ""
  backup:
    # 3-day retention for both base backups and WALs
    retentionPolicy: "3d"
    barmanObjectStore:
      destinationPath: s3://cnpg/backups/coder
      # Only needed if NOT using AWS (e.g., MinIO or DigitalOcean)
      endpointURL: http://rustfs.rustfs.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-s3-backup
spec:
  # Standard Cron: s m h dom mon dow
  # This runs every day at 2:00 AM
  schedule: "0 0 2 * * *"
  cluster:
    name: coder-postgres
  # Setting this to true takes a backup immediately upon creation
  immediate: true
  # 'self' means this ScheduledBackup object owns the resulting Backup records
  backupOwnerReference: self