apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-nfs-pv
  labels:
    type: nfs    # This matches the PVC selector
spec:
  capacity:
    storage: 5Gi # Matches the PVC storage request
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/pool1/jellyfin/media    # Replace with your NFS share path
    server: 192.168.0.15                  # Replace with your NFS server IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: nfs  # Add selector to match PV label
  storageClassName: "" # This prevents dynamic provisioning
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs
  namespace: default
spec:
  containers:
    - name: app
      image: alpine
      volumeMounts:
      - name: data
        mountPath: /var/nfs
      command: ["/bin/sh"]
      args: ["-c", "sleep 500000"]
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: myapp-nfs