--
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: nfs  # Add selector to match PV label
---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-using-nfs
#   namespace: default
# spec:
#   containers:
#     - name: app
#       image: alpine
#       volumeMounts:
#       - name: data
#         mountPath: /var/nfs
#       command: ["/bin/sh"]
#       args: ["-c", "sleep 500000"]
#   volumes:
#   - name: data
#     persistentVolumeClaim:
#       claimName: myapp-nfs