apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-persistent-storage
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: nginx-html-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-pvc
spec:
  storageClassName: nfs-csi # Change to your specific StorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi