apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  labels:
    app.kubernetes.io/name: csi-driver-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.15
  share: /mnt/pool1/k8s/nfs
  # Permission and ownership controls
  mountPermissions: "0777"  # Global RWX (will be root-owned)
  # Alternative strict permissions:
  # mountPermissions: "0755"  # Owner RWX, others RX
mountOptions:
  - nfsvers=4.1
  - noatime
  - async  # Better for torrent writes
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true