apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    $patch: replace
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: rustfs
          image: IMAGE_PLACEHOLDERi"
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-data
