apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/component: tv-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8989
    targetPort: 8989
  selector:
    app: sonarr