apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      imagePullSecrets:
        - name: regcred-ghcr
      containers:
        - name: backstage
          image: IMAGE_NAME # Replace with the actual image name
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-secrets
                  key: password
            - name: POSTGRES_HOST
              value: backstage-postgres-rw.backstage.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: backstage
          # envFrom:
          #   - secretRef:
          #       name: backstage-secrets