apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-postgres
spec:
  # At the time of writing, immich is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba # UID 26, GID 999
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  managed:
    roles:
      - name: backstage
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: backstage
      owner: backstage
      secret:
        name: backstage-postgres-secrets
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          service: backstage-postgres-data
      storageClassName: ""