---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backstage-postgres-data
  labels:
    service: backstage-postgres-data  # This matches the PVC selector
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16 # change me
    path: /mnt/pool1/AppData/cnpg/backstage
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - noatime
    - nfsvers=4.2