apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
  labels:
    service: media-stack    # This matches the PVC selector
spec:
  capacity:
    storage: 250Gi
  nfs:
    server: 192.168.0.15 # change me
    path: /mnt/pool1/jellyfin/media
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  selector:
    matchLabels:
      service: media-stack  # Add selector to match PV label
  volumeName: media-data
  storageClassName: "" # This prevents dynamic provisioning
# ---
# # Application-specific config volumes
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jellyfin-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jellyfin-cache
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: qbittorrent-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lidarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: overseerr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: radarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: readarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: tdarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi  # Larger for plugin cache
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sonarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prowlarr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jellyseerr-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: gluetun-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-stack-config
  labels:
    service: media-stack-config   # This matches the PVC selector
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.0.15 # change me
    path: /mnt/pool1/AppData/
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stack-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      service: media-stack-config # Add selector to match PV label
  volumeName: media-stack-config
  storageClassName: "" # This prevents dynamic provisioning