apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  type: ClusterIP  # Or LoadBalancer/ClusterIP based on needs
  selector:
    app: flaresolverr
  ports:
  - port: 8191
    targetPort: 8191
    name: http