apiVersion: v1
kind: PersistentVolume
metadata:
  name: etc-pihole
  labels:
    service: etc-pihole  # This matches the PVC selector
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16 # change me
    path: /mnt/pool1/AppData/
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: etc-pihole # Add selector to match PV label
  storageClassName: "" # This prevents dynamic provisioning
