apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data
  labels:
    service: uptime-kuma-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/k8s-storage/uptime-kuma
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: uptime-kuma-data
  storageClassName: ""
