---
- name: Remediate Worker Node Security Configuration
  hosts: workers
  become: yes
  tasks:

    # 4.1.1 Ensure kubelet service file permissions are 600
    - name: Set permissions on kubelet service file
      file:
        path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
        mode: '0600'
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

    # 4.1.2 Ensure kubelet service file ownership is root:root (already PASS, but included for idempotency)
    - name: Set ownership on kubelet service file
      file:
        path: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
        owner: root
        group: root

    # 4.1.3/4.1.4 If proxy kubeconfig exists, set permissions/ownership
    - name: Set permissions on proxy kubeconfig if exists
      file:
        path: /etc/kubernetes/proxy.conf
        mode: '0600'
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'
      ignore_errors: yes

    - name: Set ownership on proxy kubeconfig if exists
      file:
        path: /etc/kubernetes/proxy.conf
        owner: root
        group: root
      ignore_errors: yes

    # 4.1.5/4.1.6 kubelet.conf permissions/ownership
    - name: Set permissions on kubelet.conf
      file:
        path: /etc/kubernetes/kubelet.conf
        mode: '0600'

    - name: Set ownership on kubelet.conf
      file:
        path: /etc/kubernetes/kubelet.conf
        owner: root
        group: root

    # 4.1.7/4.1.8 client-ca-file permissions/ownership (if exists)
    - name: Set permissions on client-ca-file if exists
      file:
        path: /etc/kubernetes/pki/ca.crt
        mode: '0600'
      ignore_errors: yes

    - name: Set ownership on client-ca-file if exists
      file:
        path: /etc/kubernetes/pki/ca.crt
        owner: root
        group: root
      ignore_errors: yes

    # 4.1.9/4.1.10 kubelet config.yaml permissions/ownership
    - name: Set permissions on kubelet config.yaml
      file:
        path: /var/lib/kubelet/config.yaml
        mode: '0600'
      ignore_errors: yes

    - name: Set ownership on kubelet config.yaml
      file:
        path: /var/lib/kubelet/config.yaml
        owner: root
        group: root
      ignore_errors: yes

    # 4.2.1/4.2.2/4.2.3/4.2.12: Ensure kubelet config file has correct settings
    - name: Patch kubelet config.yaml for security settings
      blockinfile:
        path: /var/lib/kubelet/config.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK: CIS Kubelet Security"
        block: |
          authentication:
            anonymous:
              enabled: false
            x509:
              clientCAFile: "/etc/kubernetes/pki/ca.crt"
          authorization:
            mode: Webhook
          tlsCipherSuites:
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_RSA_WITH_AES_256_GCM_SHA384
            - TLS_RSA_WITH_AES_128_GCM_SHA256
      ignore_errors: yes

    # 4.2.9: Ensure tlsCertFile and tlsPrivateKeyFile are set (edit as needed for your paths)
    - name: Ensure tlsCertFile and tlsPrivateKeyFile are set in kubelet config
      blockinfile:
        path: /var/lib/kubelet/config.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK: Kubelet TLS"
        block: |
          tlsCertFile: "/var/lib/kubelet/pki/kubelet.crt"
          tlsPrivateKeyFile: "/var/lib/kubelet/pki/kubelet.key"
      ignore_errors: yes

    # Restart kubelet to apply changes
    - name: Reload systemd and restart kubelet
      systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes