- name: Setup Kubernetes Context
  hosts: control-plane  # Adjust as needed
  become: true
  vars:
    kube_user: ubuntu
    kube_config_dir: "/home/{{ kube_user }}/.kube"
    kube_admin_config: /etc/kubernetes/admin.conf
  
  tasks:
    - name: Create .kube directory
      file:
        path: "{{ kube_config_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ kube_user }}"
        group: "{{ kube_user }}"

    - name: Check if admin.conf exists
      stat:
        path: "{{ kube_admin_config }}"
      register: admin_conf

    - name: Fail if admin.conf doesn't exist
      fail:
        msg: "Kubernetes admin.conf file not found at {{ kube_admin_config }}"
      when: not admin_conf.stat.exists

    - name: Copy admin.conf to user's kube config
      copy:
        src: "{{ kube_admin_config }}"
        dest: "{{ kube_config_dir }}/config"
        remote_src: yes
        mode: '0600'
        owner: "{{ kube_user }}"
        group: "{{ kube_user }}"

    - name: Verify kubeconfig works
      command: kubectl get nodes
      register: kubectl_test
      changed_when: false
      become: false
      become_user: "{{ kube_user }}"
      ignore_errors: true

    - name: Show kubectl test results
      debug:
        var: kubectl_test.stdout_lines
      when: kubectl_test is success
