- name: Kubernetes Dependencies
  hosts: workers 
  become: yes
  tasks:

    - name: Updates
      apt:
        update_cache: yes
      tags: prerequisites

    - name: Install prerequisites
      apt:
        name:
          - nfs-common
          - open-iscsi
        state: present
        update_cache: yes
      tags: prerequisites

- hosts: k8s-control-plane-1
  become: yes
  tasks:
    - name: Install longhorn
      shell:  |-
        set -e
        kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml
        kubectl patch svc longhorn-frontend -n longhorn-system --type='json' -p='[{"op": "add", "path": "/spec/type", "value": "LoadBalancer"}]'
        kubectl get svc longhorn-frontend -n longhorn-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      args:
        chdir: $HOME
      tags: longhorn

    # - name: Create longhorn storage class
    #   shell: kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/examples/storageclass.yaml
    #   args:
    #     chdir: $HOME
    #   tags: longhorn

    # - name: Patch longhorn storage class
    #   shell: |-
    #     kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
    #   args:
    #     chdir: $HOME
    #   tags: longhorn

    - name: Deploy pvc test
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: longhorn-volv-pvc
            namespace: default
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: longhorn
            resources:
              requests:
                storage: 1Gi
      tags: longhorn

    - name: Deploy volume test app
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: volume-test
            namespace: default
          spec:
            containers:
            - name: volume-test
              image: nginx:stable-alpine
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - name: volv
                mountPath: /data
              ports:
              - containerPort: 80
            volumes:
            - name: volv
              persistentVolumeClaim:
                claimName: longhorn-volv-pvc
      tags: longhorn