argocd_openid_client_secret: +jUxc/mKM3suHue3kEHnr5Xy9KZwamHGBBx2AmYoL8w=
argocd_openid_issuer_url: https://auth.jazziro.com/application/o/argocd/
argocd_openid_redirect_uri: https://argocd.local.jazziro.com/api/dex/callback
argocd_domain: argocd.local.jazziro.com
cloudflared_hostname_1: catalog.jazziro.com
cloudflared_hostname_2: auth.jazziro.com
cloudflared_hostname_3: vaultwarden.jazziro.com
cloudflared_hostname_4: photos.jazziro.com
cloudflared_hostname_5: imax.jazziro.com
db_encryption_key: 9d50b2d98bd163022f074e207a517f1ba8483ea1469a3e6d1eba2c65fd232cb8
argocd_domain: argocd.local.jazziro.com
authentik_secret_key: wCFQTncvyQfoU/meuHMTi5x5vSOEewn79E1G5X25rsSDRcsSv3zSsjjjJDT9Ew0+BQo643UoofSZGnOE
authentik_postgresql_password: 5W8Xc5m/pysWGMvKbkzlvaVkpvHUbz9d6q0DUfwpYpUcDZQ1
s3_access_key: oz9HO6Fq1L5NwJfBxrsR
s3_secret_key: 1Kvja3ShkifmE5hkhv9DmQdJBRtDgBzAQKviPlUs
s3_endpoint: s3.local.jazziro.com 
ingress_httpd_test_host: httpd-test.local.jazziro.com
gitea_db_name: gitea
gitea_db_password: gitea12345
gitea_db_user: gitea
gitea_db_repmgr_password: gitea-repmgr
gitea_admin_username: root
gitea_admin_password: Gitea@homelab
gitea_admin_email: root@jazziro.com
gitea_domain: git.jazziro.com