apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/component: movie-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7878
    targetPort: 7878
  selector:
    app: radarr