
# Webtop
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT-2
      # - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./config:/config
      # - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 4000:3000
      - 4001:3001
    deploy:
      resources:
        limits:
          cpus: "1" # Limit CPU core
          memory: 4G # Limit RAM
        reservations:
          cpus: "0.5" # Guaranteed minimum CPU
          memory: 2G # Guaranteed minimum RAM
    # devices:
    #   - /dev/dri:/dev/dri #optional
    shm_size: 1gb #optional
    restart: unless-stopped
networks: {}