---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: databasus-data
  labels:
    service: databasus-data    # This matches the PVC selector
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.16 # change me
    path: /mnt/pool2/AppData/databasus
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databasus-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: databasus-data # Add selector to match PV label
  volumeName: databasus-data
  storageClassName: "" # This prevents dynamic provisioning