image:
  registry: dhi.io
  repository: traefik
  tag: "3"
  pullPolicy: IfNotPresent

versionOverride: v3.6.12

additionalArguments:
  - "--accessLog=true"
  - "--accessLog.filePath=/dev/stdout"
  - "--accessLog.format=json"
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--entryPoints.web.transport.respondingTimeouts.readTimeout=0s"
  - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=0s"

experimental:
  kubernetesGateway:
    enabled: true

deployment:
  enabled: true
  kind: DaemonSet
  imagePullSecrets:
    - name: dhi-secret
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

service:
  enabled: true
  type: ClusterIP

ports:
  web:
    port: 8000
    containerPort: 8000
    hostPort: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    observability: {}

  websecure:
    port: 8443
    containerPort: 8443
    hostPort: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    observability: {}

  postgres:
    port: 5432
    expose:
      default: true
    exposedPort: 5432
    protocol: TCP
    observability: {}

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik
    allowExternalNameServices: true

  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

  kubernetesGateway:
    enabled: true
    experimentalChannel: true

rbac:
  enabled: true