apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/component: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/component: media-server
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: shared-permissions
        - configMapRef:
            name: global-env
        ports:
        - containerPort: 8096
          name: http
        - containerPort: 8920
          name: https
        volumeMounts:
        - name: media-stack-config
          mountPath: /config
          subPath: jellyfin/config
        - name: media-stack-config
          mountPath: /cache
          subPath: jellyfin/cache
        - name: data
          mountPath: /data/media
          readOnly: true  # Jellyfin only needs read access
        resources:
          requests:
            cpu: "512m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: media-stack-config
        persistentVolumeClaim:
          claimName: media-stack-config