apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/component: media-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/component: media-server
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin
        securityContext:
          capabilities:
            drop: ["ALL"]
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: shared-permissions
        - configMapRef:
            name: global-env
        ports:
        - containerPort: 8096
          name: http
        - containerPort: 8920
          name: https
        volumeMounts:
        - name: media-stack-config
          mountPath: /config
          subPath: jellyfin/config
        - name: media-stack-config
          mountPath: /cache
          subPath: jellyfin/cache
        - name: data
          mountPath: /data/media
          readOnly: true  # Jellyfin only needs read access
        resources:
          requests:
            cpu: "128m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: media-stack-config
        persistentVolumeClaim:
          claimName: media-stack-config