apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace configuration
namespace: gitea

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: gitea-postgres-secrets
  envs:
    - .env
resources:
- ../../base