apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/component: music-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8686
    targetPort: 8686
  selector:
    app: lidarr