apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: IMAGE_TEMPLATE
  newName: jc21/nginx-proxy-manager
  newTag: 2.12.3

patches:
- path: ./patch.yaml

namespace: nginx-proxy-manager