---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app: n8n
spec:
  $patch: replace
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      service: n8n-data
  storageClassName: ""
