apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zero-trust

# update image
images:
- name: IMAGE_TEMPLATE
  newName: vaultwarden/server
  newTag: latest

# Shared resources across all apps
resources:
- ../../base