services:
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    networks:
      - net
    env_file:
      - .env
    environment:
      POSTGRESQL_HOSTNAME: db
      POSTGRESQL_DATABASE: ${POSTGRES_DATABASE}
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      GUACD_HOSTNAME: guacd
    ports:
      - 8080:8080
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - net
  db:
    image: postgres:17-bookworm
    user: root
    restart: on-failure
    container_name: postgres-db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    networks:
      - net