clusters:
  # List of Proxmox clusters
  - url: https://192.168.0.11:8006/api2/json
    # Skip the certificate verification, if needed
    insecure: false
    # Proxmox api token
    token_id: "kubernetes-csi@pve!csi"
    token_secret: "secret"
    # Region name, which is cluster name
    region: kubelab
# Define the storage classes
storageClass:
  - name: proxmox-data-xfs
    storage: data
    reclaimPolicy: Delete
    fstype: xfs
    # Define the storage class as default
    # annotations:
    #   storageclass.kubernetes.io/is-default-class: "true"